-- ════════════════════════════════════════════════════════════════════
--  DOCUMENT REGISTER — physical document custody log (2026-08-01)
--
--  Backs the File Management module (sidebar core module, "Document
--  Register" is the underlying name). A stock-register-style log for
--  paper documents clients drop off (Purchase/Sales Files, Ledger,
--  Confirmation, Interest Certificate, ...) and their eventual handover
--  back — deliberately one row per visit, updated in place when the
--  documents are returned, rather than a separate returns table.
--
--  · register_no   assigned by an AFTER INSERT trigger, mirroring
--                   public.set_service_memo_number: 'FM-' || lpad(id,5,'0').
--  · client_id      nullable FK — a walk-in not yet in the directory still
--                    saves; name/pan are snapshotted regardless (same
--                    discipline as service_memos/invoices).
--  · doc_types      jsonb array of the fixed FM_DOC_TYPES picklist
--                    (window.FM_DOC_TYPES in js/config.js); doc_other holds
--                    the free-text "Others" entry.
--  · status         pending / returned. Every transition goes through
--                    WorkflowEngine.createStatusFlow in js/fileManagement.js
--                    (fmFlow) so the badge, the persisted row and the audit
--                    entry can never disagree — mirrors vatCompliance.js.
--  · date_returned / returned_to_name / returned_to_phone / return_remarks
--                    filled only on the pending -> returned transition;
--                    cleared again if reopened (pending mistake correction).
--
--  RLS: members (app_users) get full CRUD — working data, mirroring
--  service_memos / vat_filings / depreciation_schedules. New table =>
--  policies added here, or the app can't read it at all (CLAUDE.md §6).
--  Uses private.is_app_user().
--
--  Rollback: db/2026-08-01_document_register_rollback.sql
-- ════════════════════════════════════════════════════════════════════

create table if not exists public.document_register (
  id                 bigint generated by default as identity primary key,
  register_no        text,                              -- trigger-assigned, e.g. FM-00001
  client_id          bigint references public.clients(id) on delete set null,
  client_name        text   not null,                    -- snapshot at save time
  client_pan         text,                                -- snapshot
  date_received      date   not null default current_date,
  doc_types          jsonb  not null default '[]'::jsonb, -- e.g. ["Ledger","Confirmation"]
  doc_other          text,                                -- free text when "Others" is ticked
  brought_by_name    text   not null,
  brought_by_phone   text,
  remarks            text,
  status             text   not null default 'pending'
                     check (status in ('pending', 'returned')),
  date_returned      date,
  returned_to_name   text,
  returned_to_phone  text,
  return_remarks     text,
  created_by         text,
  updated_by         text,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

comment on table public.document_register is
  'Physical document intake/handover log (File Management module) — one row per visit, updated on return.';

create index if not exists document_register_client_idx     on public.document_register (client_id);
create index if not exists document_register_status_idx     on public.document_register (status);
create index if not exists document_register_created_idx    on public.document_register (created_at desc);

-- ── Auto register number (AFTER INSERT, mirrors public.set_service_memo_number) ──
create or replace function public.set_document_register_number()
  returns trigger
  language plpgsql
  set search_path to ''
as $function$
begin
  if new.register_no is null then
    update public.document_register
      set register_no = 'FM-' || lpad(new.id::text, 5, '0')
      where id = new.id;
  end if;
  return null;
end $function$;

drop trigger if exists set_document_register_number on public.document_register;
create trigger set_document_register_number
  after insert on public.document_register
  for each row execute function public.set_document_register_number();

-- ── updated_at maintenance (reuses the shared trigger fn) ──
drop trigger if exists set_document_register_updated_at on public.document_register;
create trigger set_document_register_updated_at
  before update on public.document_register
  for each row execute function public.set_updated_at();

-- ── RLS: full member CRUD. Non-members / anon get zero rows. ──
alter table public.document_register enable row level security;

drop policy if exists document_register_select_member on public.document_register;
create policy document_register_select_member on public.document_register
  for select to authenticated using (private.is_app_user());

drop policy if exists document_register_insert_member on public.document_register;
create policy document_register_insert_member on public.document_register
  for insert to authenticated with check (private.is_app_user());

drop policy if exists document_register_update_member on public.document_register;
create policy document_register_update_member on public.document_register
  for update to authenticated using (private.is_app_user()) with check (private.is_app_user());

drop policy if exists document_register_delete_member on public.document_register;
create policy document_register_delete_member on public.document_register
  for delete to authenticated using (private.is_app_user());
