-- ════════════════════════════════════════════════════════════════════
--  PROJECTION REPORTS — saved bank-projection workings (2026-07-22)
--
--  Backs the Projection Report module (§5.15). One row = one generated
--  multi-year projection for a client: the parsed statement snapshot,
--  the assumptions the accountant entered (growth %, loans, additions,
--  overrides), and the fully computed result (statements, ratios, solver
--  decisions per year). Saving the `computed` jsonb makes a report
--  reproducible and auditable without re-uploading the source workbook,
--  and gives next year's projection a carry-forward base.
--
--  · client_id   nullable FK — a projection for a company not yet in the
--                directory still saves; name/pan snapshotted regardless.
--  · inputs      jsonb: { parsedModel, assumptions } — everything needed
--                to re-run ProjectionEngine.project() exactly.
--  · computed    jsonb: the project() output (years[], ird, meta) at the
--                moment of saving — statements, ratios, levers.
--  · fiscal_year_base  dash format of the audited year, e.g. '2082-83'.
--
--  RLS: members (app_users) get full CRUD — working data, mirroring
--  service_memos / depreciation_schedules. New table => policies added
--  in this same migration or the app can't read it at all (§6.6).
--
--  Rollback: db/2026-07-22_projection_reports_rollback.sql
-- ════════════════════════════════════════════════════════════════════

create table if not exists public.projection_reports (
  id                bigint generated by default as identity primary key,
  client_id         bigint references public.clients(id) on delete set null,
  company_name      text   not null,                   -- snapshot at save time
  pan               text,                              -- snapshot
  fiscal_year_base  text   not null,                   -- audited FY, dash format
  years             int    not null default 3 check (years between 1 and 10),
  inputs            jsonb  not null default '{}'::jsonb,
  computed          jsonb  not null default '{}'::jsonb,
  created_by        text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

comment on table public.projection_reports is
  'Saved multi-year financial projections (Projection Report module): parsed statement + assumptions in `inputs`, full engine output in `computed`.';

create index if not exists projection_reports_client_idx  on public.projection_reports (client_id);
create index if not exists projection_reports_fy_idx      on public.projection_reports (fiscal_year_base);
create index if not exists projection_reports_created_idx on public.projection_reports (created_at desc);

-- ── updated_at maintenance (reuses the shared trigger fn) ──
drop trigger if exists set_projection_reports_updated_at on public.projection_reports;
create trigger set_projection_reports_updated_at
  before update on public.projection_reports
  for each row execute function public.set_updated_at();

-- ── RLS: full member CRUD. Non-members / anon get zero rows. ──
alter table public.projection_reports enable row level security;

drop policy if exists projection_reports_select_member on public.projection_reports;
create policy projection_reports_select_member on public.projection_reports
  for select to authenticated using (private.is_app_user());

drop policy if exists projection_reports_insert_member on public.projection_reports;
create policy projection_reports_insert_member on public.projection_reports
  for insert to authenticated with check (private.is_app_user());

drop policy if exists projection_reports_update_member on public.projection_reports;
create policy projection_reports_update_member on public.projection_reports
  for update to authenticated using (private.is_app_user()) with check (private.is_app_user());

drop policy if exists projection_reports_delete_member on public.projection_reports;
create policy projection_reports_delete_member on public.projection_reports
  for delete to authenticated using (private.is_app_user());
