-- ════════════════════════════════════════════════════════════════════
--  BANK BOOK — receipts & payments ledger for the firm's own bank
--  accounts (2026-07-22)
--
--  Backs the Bank Book module (topbar Accounting menu). This is the
--  firm's INTERNAL bookkeeping across its own bank accounts — not a
--  client-facing document (Billing / Service Memo are). Two tables:
--
--  · bank_accounts       the Add/Edit/Delete master. One row per
--                        (holder, bank, account number) with an opening
--                        balance anchored at a B.S. date (FY start).
--                        The holder/bank list is DATA here, not JS config
--                        (unlike SERVICE_MEMO_FIRMS) — it is user-managed.
--
--  · bank_transactions   one row per receipt or payment. Particular is
--                        fee_receipt / expenses / sapati / inter_bank_transfer.
--                        An inter-bank transfer is recorded as TWO paired
--                        rows sharing transfer_group_id: a `payment` on the
--                        source account and a `receipt` on the destination,
--                        so the two legs can never disagree (the app edits/
--                        deletes both together). client_id links a Fee
--                        Receipt to the directory; counterparty_account_id
--                        is the other leg's account for a transfer.
--
--  Running balances (statement) are derived at read time in JS from
--  opening_balance + ordered receipts/payments — never stored (same
--  discipline as billing overdue / SLM closing, CLAUDE.md §16). No
--  memo-number-style trigger: transactions carry no external number.
--
--  RLS: members (app_users) get full CRUD — working data, mirroring
--  vat_filings / service_memos. New tables => policies added here, or the
--  app can't read them at all (§6.6). Uses private.is_app_user().
--
--  Rollback: db/2026-07-22_bank_book_rollback.sql
-- ════════════════════════════════════════════════════════════════════

-- ── Accounts master ──────────────────────────────────────────────────
create table if not exists public.bank_accounts (
  id              bigint generated by default as identity primary key,
  account_name    text   not null,                 -- holder, e.g. "Shailesh & Associates"
  bank_name       text   not null,
  account_number  text,                             -- text: preserves leading zeros (§6.3)
  opening_balance numeric(16,2) not null default 0,
  opening_date    text,                             -- B.S. date the opening balance is "as on" (e.g. '2083.04.01')
  is_active       boolean not null default true,    -- soft-deactivate instead of deleting accounts with history
  sort_order      int     not null default 0,
  created_by      text,
  updated_by      text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

comment on table public.bank_accounts is
  'Firm-owned bank accounts (Bank Book module). Holder/bank list is user-managed data, not JS config.';

create index if not exists bank_accounts_active_idx on public.bank_accounts (is_active);
create index if not exists bank_accounts_sort_idx   on public.bank_accounts (sort_order);

-- ── Transactions (receipts & payments) ───────────────────────────────
create table if not exists public.bank_transactions (
  id                      bigint generated by default as identity primary key,
  account_id              bigint not null references public.bank_accounts(id) on delete restrict,
  txn_type                text   not null check (txn_type in ('receipt', 'payment')),
  txn_date                text   not null,          -- B.S. date 'YYYY.MM.DD' (validated in JS)
  particular              text   not null
                          check (particular in ('fee_receipt', 'expenses', 'sapati', 'inter_bank_transfer')),
  amount                  numeric(16,2) not null check (amount > 0),
  counterparty_name       text,                     -- client / person / nature-of-expense snapshot
  client_id               bigint references public.clients(id) on delete set null,      -- Fee Receipt link only
  counterparty_account_id bigint references public.bank_accounts(id) on delete set null, -- other leg's account (transfers)
  transfer_group_id       uuid,                     -- shared by the two legs of one inter-bank transfer
  description             text,
  fiscal_year             text,                     -- dash format (e.g. '2083-84'), derived from txn_date
  created_by              text,
  updated_by              text,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

comment on table public.bank_transactions is
  'Bank Book receipts & payments. Inter-bank transfers = two paired rows sharing transfer_group_id (payment leg + receipt leg).';

create index if not exists bank_transactions_account_idx  on public.bank_transactions (account_id);
create index if not exists bank_transactions_type_idx     on public.bank_transactions (txn_type);
create index if not exists bank_transactions_fy_idx       on public.bank_transactions (fiscal_year);
create index if not exists bank_transactions_date_idx     on public.bank_transactions (txn_date);
create index if not exists bank_transactions_transfer_idx on public.bank_transactions (transfer_group_id);

-- ── updated_at maintenance (reuses the shared trigger fn) ─────────────
drop trigger if exists set_bank_accounts_updated_at on public.bank_accounts;
create trigger set_bank_accounts_updated_at
  before update on public.bank_accounts
  for each row execute function public.set_updated_at();

drop trigger if exists set_bank_transactions_updated_at on public.bank_transactions;
create trigger set_bank_transactions_updated_at
  before update on public.bank_transactions
  for each row execute function public.set_updated_at();

-- ── RLS: full member CRUD. Non-members / anon get zero rows. ─────────
alter table public.bank_accounts     enable row level security;
alter table public.bank_transactions enable row level security;

-- bank_accounts
drop policy if exists bank_accounts_select_member on public.bank_accounts;
create policy bank_accounts_select_member on public.bank_accounts
  for select to authenticated using (private.is_app_user());

drop policy if exists bank_accounts_insert_member on public.bank_accounts;
create policy bank_accounts_insert_member on public.bank_accounts
  for insert to authenticated with check (private.is_app_user());

drop policy if exists bank_accounts_update_member on public.bank_accounts;
create policy bank_accounts_update_member on public.bank_accounts
  for update to authenticated using (private.is_app_user()) with check (private.is_app_user());

drop policy if exists bank_accounts_delete_member on public.bank_accounts;
create policy bank_accounts_delete_member on public.bank_accounts
  for delete to authenticated using (private.is_app_user());

-- bank_transactions
drop policy if exists bank_transactions_select_member on public.bank_transactions;
create policy bank_transactions_select_member on public.bank_transactions
  for select to authenticated using (private.is_app_user());

drop policy if exists bank_transactions_insert_member on public.bank_transactions;
create policy bank_transactions_insert_member on public.bank_transactions
  for insert to authenticated with check (private.is_app_user());

drop policy if exists bank_transactions_update_member on public.bank_transactions;
create policy bank_transactions_update_member on public.bank_transactions
  for update to authenticated using (private.is_app_user()) with check (private.is_app_user());

drop policy if exists bank_transactions_delete_member on public.bank_transactions;
create policy bank_transactions_delete_member on public.bank_transactions
  for delete to authenticated using (private.is_app_user());
