-- ════════════════════════════════════════════════════════════════════
--  SAVED DOCUMENTS — re-openable output of the HTML document builders
--  (2026-08-02)
--
--  Backs js/core/documentStore.js, shared today by the Audit Report
--  Builder (§5.5) and Notes to Accounts (§5.6). One row = one saved
--  document. Deliberately ONE table with a `module` discriminator rather
--  than one table per builder: every builder stores the same two things
--  (the form state and the rendered document), so per-module tables would
--  duplicate the schema, the RLS block and the whole save/list/restore UI
--  for no gain — and the next builder that wants "save & revisit" gets it
--  by adding one value to the CHECK.
--
--  · state     jsonb — the form field values, so a saved document can be
--              re-opened, EDITED and re-generated.
--  · doc_html  text  — the rendered document at the moment of saving. The
--              preview is contenteditable, so the state alone cannot
--              reproduce a hand-edited document; this is what makes
--              "reprint exactly what I sent the client" true.
--  · client_id nullable FK — a document for a company not in the
--              directory still saves; name/pan are snapshotted regardless
--              (same immutable-trail convention as the log tables).
--
--  RLS: members (app_users) get full CRUD — working data, mirroring
--  projection_reports / financial_statements. New table => policies in
--  this same migration or the app cannot read it at all (§6).
--
--  Rollback: db/2026-08-02_saved_documents_rollback.sql
-- ════════════════════════════════════════════════════════════════════

create table if not exists public.saved_documents (
  id           bigint generated by default as identity primary key,
  module       text   not null check (module in ('report', 'notesToAccounts')),
  client_id    bigint references public.clients(id) on delete set null,
  client_name  text   not null,               -- snapshot at save time
  pan          text,                          -- snapshot
  fiscal_year  text,                          -- dash format, e.g. '2081-82'
  doc_type     text,                          -- report type key, e.g. 'unqualified'
  title        text   not null,               -- what the picker lists
  state        jsonb  not null default '{}'::jsonb,
  doc_html     text,
  created_by   text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

comment on table public.saved_documents is
  'Saved output of the HTML document builders (Audit Report, Notes to Accounts): editable form state in `state`, the rendered document in `doc_html`. One row per saved document, discriminated by `module`.';

create index if not exists saved_documents_module_idx  on public.saved_documents (module, created_at desc);
create index if not exists saved_documents_client_idx  on public.saved_documents (client_id);

-- ── updated_at maintenance (reuses the shared trigger fn) ──
drop trigger if exists set_saved_documents_updated_at on public.saved_documents;
create trigger set_saved_documents_updated_at
  before update on public.saved_documents
  for each row execute function public.set_updated_at();

-- ── RLS: full member CRUD. Non-members / anon get zero rows. ──
alter table public.saved_documents enable row level security;

drop policy if exists saved_documents_select_member on public.saved_documents;
create policy saved_documents_select_member on public.saved_documents
  for select to authenticated using (private.is_app_user());

drop policy if exists saved_documents_insert_member on public.saved_documents;
create policy saved_documents_insert_member on public.saved_documents
  for insert to authenticated with check (private.is_app_user());

drop policy if exists saved_documents_update_member on public.saved_documents;
create policy saved_documents_update_member on public.saved_documents
  for update to authenticated using (private.is_app_user()) with check (private.is_app_user());

drop policy if exists saved_documents_delete_member on public.saved_documents;
create policy saved_documents_delete_member on public.saved_documents
  for delete to authenticated using (private.is_app_user());
