-- ════════════════════════════════════════════════════════════════════════════
--  STAGE 3 — invitations and member management
--
--  Part of the multi-tenant conversion. Full roadmap:
--  https://claude.ai/code/artifact/341550a6-dab5-4ee4-bb83-d2fc381941d6
--
--  Depends on: Stage 2 Phases 1–3 (organizations / org_members /
--  current_org_id() / org-scoped policies).
--
--  THE PROBLEM THIS SOLVES
--    Every account for every firm is currently created by hand in the Supabase
--    dashboard, by the one person who has access to all ten firms' data. That
--    does not scale to ~60 users and it means an outside firm cannot add its
--    own staff without asking.
--
--  WHY THIS IS AN RPC AND NOT A SERVER
--    Creating an auth account normally needs the service-role key, which must
--    never reach a browser (CLAUDE.md §13), and this app deliberately has no
--    backend (§2). Two SECURITY DEFINER functions are the backend: they run
--    inside Postgres with the privileges to do the one specific thing needed,
--    and the browser can only call them with the arguments they validate.
--    No Edge Function, no companion process, no secret in the client.
--
--  THE FLOW, AND WHY IT SENDS NO EMAIL
--    1. An admin calls create_invitation(email, role). It returns a random
--       token ONCE and stores only its SHA-256 hash.
--    2. The admin sends the resulting link to their colleague however they
--       already communicate — WhatsApp, their own email, on paper.
--    3. The colleague signs up with that email and a password they choose,
--       then the app calls accept_invitation(token), which creates their
--       org_members row with the role the invitation named.
--
--    The app never sends mail, so Supabase's built-in SMTP rate limit (a few
--    an hour, shared across the whole project) cannot throttle onboarding.
--    That limit is a real constraint for password resets; it is not allowed to
--    become one for invitations.
--
--  ENABLING SIGNUP IS SAFE, AND REQUIRED
--    This needs "Allow new users to sign up" ON in the Supabase dashboard,
--    which is currently off. An auth account with no org_members row is inert:
--    every policy in the database requires membership AND organisation match,
--    so a stranger who signs up sees nothing at all and can write nothing.
--    Access begins at accept_invitation(), not at signup.
--
--  ROLLBACK: db/2026-08-18_stage3_invitations_rollback.sql
-- ════════════════════════════════════════════════════════════════════════════


-- ── 1. The invitation record ────────────────────────────────────────────────
-- The raw token is NEVER stored. It is shown to the admin once, at creation,
-- and thereafter only its hash exists — so a leaked database backup cannot be
-- used to join anyone's organisation. Same reasoning as storing a password
-- hash rather than a password.
create table public.org_invitations (
  id           bigint generated by default as identity primary key,
  org_id       bigint not null references public.organizations(id) on delete cascade,
  email        text   not null,
  role         text   not null default 'staff',
  token_hash   text   not null unique,
  expires_at   timestamptz not null,
  accepted_at  timestamptz,
  accepted_by  text,
  revoked_at   timestamptz,
  created_by   text,
  created_at   timestamptz not null default now(),
  constraint org_invitations_role_check
    check (role = any (array['owner','admin','staff'])),
  -- Email is stored already-lowercased so the lookup in accept_invitation is a
  -- plain equality against private.jwt_email(), which also lowercases. Same
  -- rule that makes auth.js use .ilike() rather than .eq() (CLAUDE.md §7).
  constraint org_invitations_email_lower
    check (email = lower(email))
);

create index org_invitations_org_idx   on public.org_invitations (org_id);
create index org_invitations_email_idx on public.org_invitations (email);

alter table public.org_invitations enable row level security;

-- Admins see and manage invitations for their OWN organisation only. There is
-- deliberately no INSERT policy: invitations are created through
-- create_invitation(), which is what guarantees the token is random and only
-- its hash is stored. A hand-rolled INSERT could store a guessable token.
create policy org_invitations_select_admin on public.org_invitations
  for select to authenticated
  using (org_id = private.current_org_id() and private.is_admin());

create policy org_invitations_delete_admin on public.org_invitations
  for delete to authenticated
  using (org_id = private.current_org_id() and private.is_admin());

create policy org_invitations_update_admin on public.org_invitations
  for update to authenticated
  using (org_id = private.current_org_id() and private.is_admin())
  with check (org_id = private.current_org_id());


-- ── 2. Creating an invitation ───────────────────────────────────────────────
-- Returns the raw token exactly once. The caller must show it to the admin
-- immediately; it is unrecoverable afterwards.
--
-- SECURITY DEFINER, but it re-checks private.is_admin() itself rather than
-- trusting the caller — a SECURITY DEFINER function runs with the owner's
-- rights, so it must never assume RLS already filtered anything.
create or replace function public.create_invitation(
  p_email text,
  p_role  text default 'staff',
  p_days  integer default 14
)
returns table (invitation_id bigint, token text, expires_at timestamptz)
language plpgsql security definer set search_path to ''
as $function$
declare
  v_org   bigint;
  v_email text := lower(btrim(p_email));
  v_token text;
begin
  if not private.is_admin() then
    raise exception 'Only an admin or owner can invite people.';
  end if;

  v_org := private.current_org_id();
  if v_org is null then
    raise exception 'No active organisation for the current user.';
  end if;

  if v_email = '' or position('@' in v_email) = 0 then
    raise exception 'A valid email address is required.';
  end if;

  if p_role not in ('owner','admin','staff') then
    raise exception 'Unknown role: %', p_role;
  end if;

  -- One person, one organisation (the global UNIQUE on org_members.email).
  -- Catching it here gives the admin a sentence instead of a constraint error.
  if exists (select 1 from public.org_members m where m.email = v_email) then
    raise exception '% already belongs to an organisation.', v_email;
  end if;

  -- Supersede any outstanding invitation for the same address rather than
  -- accumulating several live tokens for one person.
  update public.org_invitations
     set revoked_at = now()
   where org_id = v_org and email = v_email
     and accepted_at is null and revoked_at is null;

  -- 32 random bytes, hex-encoded. Generated HERE rather than in the browser so
  -- its randomness does not depend on the client, and so the raw value exists
  -- in exactly one place for exactly one statement.
  v_token := encode(extensions.gen_random_bytes(32), 'hex');

  return query
  insert into public.org_invitations (org_id, email, role, token_hash, expires_at, created_by)
  values (
    v_org, v_email, p_role,
    encode(sha256(v_token::bytea), 'hex'),
    now() + make_interval(days => greatest(1, least(p_days, 90))),
    private.jwt_email()
  )
  returning public.org_invitations.id, v_token, public.org_invitations.expires_at;
end;
$function$;

revoke all on function public.create_invitation(text, text, integer) from public, anon;
grant execute on function public.create_invitation(text, text, integer) to authenticated;


-- ── 3. Accepting an invitation ──────────────────────────────────────────────
-- Called by someone who has just signed up and has an authenticated session
-- but NO membership yet — so every table is invisible to them and they cannot
-- insert their own org_members row. This function is the single, narrow door
-- through which a membership is created.
--
-- THE EMAIL MUST MATCH. Without that check, anyone who obtained the link could
-- sign up under any address and join the firm; the token alone would be a
-- bearer credential. Requiring the signed-in email to equal the invited email
-- means the link is only usable by the person it was addressed to.
create or replace function public.accept_invitation(p_token text)
returns table (org_id bigint, org_name text, role text)
language plpgsql security definer set search_path to ''
as $function$
declare
  v_email text := private.jwt_email();
  v_inv   public.org_invitations%rowtype;
begin
  if v_email is null or v_email = '' then
    raise exception 'You must be signed in to accept an invitation.';
  end if;

  select * into v_inv
  from public.org_invitations
  where token_hash = encode(sha256(btrim(p_token)::bytea), 'hex');

  -- One message for "no such token" and "wrong token" so a caller cannot probe
  -- for which tokens exist.
  if v_inv.id is null then
    raise exception 'This invitation link is not valid.';
  end if;
  if v_inv.revoked_at is not null then
    raise exception 'This invitation has been revoked.';
  end if;
  if v_inv.accepted_at is not null then
    raise exception 'This invitation has already been used.';
  end if;
  if v_inv.expires_at < now() then
    raise exception 'This invitation expired on %.', to_char(v_inv.expires_at, 'DD Mon YYYY');
  end if;
  if v_inv.email <> v_email then
    raise exception 'This invitation was issued to a different email address.';
  end if;
  if exists (select 1 from public.org_members m where m.email = v_email) then
    raise exception 'You already belong to an organisation.';
  end if;

  insert into public.org_members (org_id, email, role, status, invited_by)
  values (v_inv.org_id, v_email, v_inv.role, 'active', v_inv.created_by);

  update public.org_invitations
     set accepted_at = now(), accepted_by = v_email
   where id = v_inv.id;

  return query
  select o.id, o.name, v_inv.role
  from public.organizations o
  where o.id = v_inv.org_id;
end;
$function$;

revoke all on function public.accept_invitation(text) from public, anon;
grant execute on function public.accept_invitation(text) to authenticated;


-- ── 4. Managing members ─────────────────────────────────────────────────────
-- org_members had no write policy at all (Phase 1 left creation to the
-- dashboard). A members screen needs to deactivate someone who has left and
-- change a role, so admins get UPDATE and DELETE within their own organisation.
--
-- INSERT stays absent on purpose — accept_invitation() is the only way in, so
-- a membership cannot be conjured without a valid token.
--
-- The WITH CHECK repeats the org test because USING governs which rows may be
-- targeted and WITH CHECK governs what they may become; without it an admin
-- could move a member into another organisation.
create policy org_members_update_admin on public.org_members
  for update to authenticated
  using (org_id = private.current_org_id() and private.is_admin())
  with check (org_id = private.current_org_id());

create policy org_members_delete_admin on public.org_members
  for delete to authenticated
  using (org_id = private.current_org_id() and private.is_admin());

-- An organisation with no active owner cannot be administered by anyone in it,
-- and recovering from that needs the Supabase dashboard. Refuse the last one.
create or replace function private.guard_last_owner()
returns trigger
language plpgsql security definer set search_path to ''
as $function$
declare
  v_org  bigint := coalesce(old.org_id, new.org_id);
  v_left integer;
begin
  select count(*) into v_left
  from public.org_members m
  where m.org_id = v_org
    and m.role = 'owner'
    and m.status = 'active'
    and m.id <> old.id;

  if v_left = 0
     and (tg_op = 'DELETE'
          or new.role <> 'owner'
          or new.status <> 'active') then
    raise exception 'This is the organisation''s last active owner. Make someone else an owner first.';
  end if;

  return case when tg_op = 'DELETE' then old else new end;
end;
$function$;

create trigger guard_last_owner_update
  before update on public.org_members
  for each row when (old.role = 'owner' and old.status = 'active')
  execute function private.guard_last_owner();

create trigger guard_last_owner_delete
  before delete on public.org_members
  for each row when (old.role = 'owner' and old.status = 'active')
  execute function private.guard_last_owner();


-- ── 5. Verify ───────────────────────────────────────────────────────────────
-- Expect: invitations_table 1 · policies 3 · rpcs 2 · guards 2
select
  (select count(*) from information_schema.tables
     where table_schema='public' and table_name='org_invitations')      as invitations_table,
  (select count(*) from pg_policies
     where schemaname='public' and tablename='org_invitations')         as invitation_policies,
  (select count(*) from pg_policies
     where schemaname='public' and tablename='org_members')             as member_policies,
  (select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace
     where n.nspname='public'
       and p.proname in ('create_invitation','accept_invitation'))      as rpcs,
  (select count(*) from pg_trigger
     where tgname like 'guard_last_owner%')                             as owner_guards;
