-- ════════════════════════════════════════════════════════════════════
--  AUTOBOOKS LEDGER (2026-08-16)
--
--  Autobooks has been stateless since it shipped: upload a raw book,
--  generate a workbook, close the tab, everything is gone. That was fine
--  while the module only converted one file into another.
--
--  It stops being fine the moment the firm records CONFIRMATIONS. A signed
--  confirmation letter comes back from a customer or supplier days or weeks
--  after the book was imported, one party at a time, and the figure on it
--  has to sit beside that party's book total until the whole list is
--  reconciled. The same is true of omitted bills (a bill that surfaced after
--  the year's register was closed) and of the year-end reconciliation
--  statement's adjustment lines. None of that survives a page reload today,
--  and re-uploading the workbook to type one more confirmation figure is
--  exactly the Excel workflow this module exists to replace.
--
--  So Autobooks gains a database. Four tables, all hanging off one book:
--
--   autobooks_books        one row per (client, fiscal year) — the working
--                          session itself, plus the import-time decisions
--                          (merge map, Data Doctor overrides, correction
--                          log, typed VAT-return figures) that used to live
--                          only in module state and localStorage.
--   autobooks_entries      every bill line, BOTH registers, plus omitted
--                          bills as kind='omitted' in the same table.
--   autobooks_parties      the confirmation ledger — one row per party per
--                          register, holding the figures a human types.
--   autobooks_adjustments  the Reco statement's ad-hoc add/less lines.
--
--  WHY ONE TABLE FOR TRANSACTIONS AND OMITTED BILLS (`kind`):
--  An omitted bill has exactly the same fields as an ordinary bill — that
--  is the firm's own template's definition of one ("For Adding omiited
--  bill | Date | Bill no | Party Name | Pan No. | Tax Free | Taxable
--  Amount | Vat"). What differs is WHEN it was entered and therefore WHERE
--  it prints: the template's own note says "Omiited bill show display in
--  last of Sales Register and Purchase register after total of month
--  ashad". That is a rendering rule, not a different record. Two tables
--  would duplicate every column and every party-total query.
--
--  WHY EVERY LINE IS STORED (user decision, 2026-08-16):
--  ~1,000–1,600 rows per client-year. Storing only party totals would keep
--  the table small but would mean the register preview, the party
--  statement and the omitted-bill append only work in the live session
--  right after an upload — reopening a client next week would need the
--  workbook re-uploaded first. The whole point of the ledger is that it
--  outlives the upload.
--
--  book_key IS A GENERATED COLUMN, and it is what makes "one book per
--  client per year" enforceable. A client here may be a directory client
--  (client_id) or a name typed by hand, the same fallback
--  service_memo_fee_skips uses; a plain UNIQUE (client_id, fiscal_year)
--  would not constrain the typed-name case at all, because NULL client_id
--  never conflicts with NULL client_id in Postgres.
--
--  FISCAL YEAR FORMAT is Autobooks' own dash form ('2081-82'), matching
--  spb-fy. Per-module formats stay deliberately different (CLAUDE.md §8) —
--  this table is Autobooks-only, so it carries Autobooks' format.
--
--  fiscal_month is 1–12 with 1 = SHRAWAN (the fiscal index, CLAUDE.md §8),
--  NOT the B.S. calendar month number. Shrawan is calendar month 4.
--
--  RLS: members (app_users) get full CRUD on all four, mirroring every
--  other working-data table. New tables => policies in this same migration
--  or the app cannot read them at all (§6.6).
--
--  Rollback: db/2026-08-16_autobooks_ledger_rollback.sql
-- ════════════════════════════════════════════════════════════════════

-- ── 1. The book: one working session per client per fiscal year ──────
create table if not exists public.autobooks_books (
  id              bigint generated by default as identity primary key,
  -- Nullable FK, ON DELETE SET NULL: a book may be for a walk-in whose name
  -- was typed rather than picked from the directory, and deleting a client
  -- must not silently destroy a year of reconciled work.
  client_id       bigint references public.clients(id) on delete set null,
  client_name     text   not null,
  pan             text,
  fiscal_year     text   not null,
  reg_type        text   not null default 'vat' check (reg_type in ('vat', 'pan')),

  -- Import-time decisions, so a reopened book reproduces the same figures
  -- rather than asking the user to re-approve every merge and correction.
  merge_map       jsonb  not null default '{}'::jsonb,   -- safeKey -> canonical safeKey
  overrides       jsonb  not null default '{}'::jsonb,   -- Data Doctor row overrides
  correction_log  jsonb  not null default '[]'::jsonb,   -- feeds the Corrections sheet
  vat_return      jsonb  not null default '{}'::jsonb,   -- typed "As Per VAT Return" figures
  import_notes    jsonb  not null default '[]'::jsonb,   -- file-level notes, re-shown on reopen
  sections        jsonb  not null default '{}'::jsonb,   -- per-section import stats + column layout

  created_by      text,
  updated_by      text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),

  -- 'c:<id>' for a directory client, 'n:<lowercased name>' for a typed one.
  book_key text generated always as (
    coalesce('c:' || client_id::text, 'n:' || btrim(lower(client_name))) || '|' || fiscal_year
  ) stored
);

comment on table public.autobooks_books is
  'One Autobooks working session per client per fiscal year — the anchor for its bill lines, confirmation ledger and reconciliation adjustments.';

create unique index if not exists autobooks_books_key_uniq
  on public.autobooks_books (book_key);

create index if not exists autobooks_books_client_idx
  on public.autobooks_books (client_id, fiscal_year);

drop trigger if exists autobooks_books_set_updated_at on public.autobooks_books;
create trigger autobooks_books_set_updated_at
  before update on public.autobooks_books
  for each row execute function public.set_updated_at();

-- ── 2. Bill lines — both registers, ordinary and omitted ─────────────
create table if not exists public.autobooks_entries (
  id             bigint generated by default as identity primary key,
  book_id        bigint not null references public.autobooks_books(id) on delete cascade,
  section        text   not null check (section in ('sales', 'purchase')),

  -- 'regular' = imported with the year's register. 'omitted' = surfaced
  -- after that register was closed; prints after the Ashadh total and is
  -- separately reportable, but still counts toward the party's book total.
  kind           text   not null default 'regular' check (kind in ('regular', 'omitted')),

  -- Only meaningful on omitted bills (the entry screen's four options).
  -- A return/debit note carries the opposite sign — that sign is what makes
  -- a party's difference close (reference file: Party G, a 34,896 debit
  -- note is exactly its books-vs-confirmation gap).
  bill_type      text   check (bill_type in ('sales', 'sales_return', 'purchase', 'purchase_return')),

  bs_date        text,                                    -- '2082.11.01', or a bare month name
  fiscal_month   smallint check (fiscal_month between 1 and 12),  -- 1 = Shrawan
  bill_no        text,
  party_name     text   not null default '',
  party_key      text   not null default '',              -- spbSafeKey/spbGroupKey, post-merge
  pan            text,

  tax_free       numeric not null default 0,
  taxable        numeric not null default 0,
  vat            numeric not null default 0,
  taxable_import numeric not null default 0,
  import_vat     numeric not null default 0,
  capital        numeric not null default 0,
  capital_vat    numeric not null default 0,

  note           text,                                     -- e.g. 'Debit Note'
  source         text   not null default 'import' check (source in ('import', 'manual')),
  excel_row      integer,                                  -- provenance back to the uploaded sheet
  sort_order     integer not null default 0,
  created_at     timestamptz not null default now()
);

comment on table public.autobooks_entries is
  'Every Autobooks bill line. kind=''omitted'' marks a bill entered after the year''s register was closed — it prints after the Ashadh total but still counts toward the party total.';

create index if not exists autobooks_entries_book_idx
  on public.autobooks_entries (book_id, section, kind, fiscal_month, sort_order);

create index if not exists autobooks_entries_party_idx
  on public.autobooks_entries (book_id, section, party_key);

-- ── 3. Confirmation ledger — one row per party per register ──────────
create table if not exists public.autobooks_parties (
  id                bigint generated by default as identity primary key,
  book_id           bigint not null references public.autobooks_books(id) on delete cascade,
  section           text   not null check (section in ('sales', 'purchase')),
  party_key         text   not null,
  party_name        text   not null,
  pan               text,

  -- Everything below is TYPED BY A HUMAN, never derived. The party's book
  -- figures are computed from autobooks_entries and deliberately not stored
  -- here — storing them would let the two drift after a re-import.
  opening_balance   numeric,        -- carried from the prior year
  confirmed_taxable numeric,        -- NULL = confirmation not received yet, which
                                    -- is NOT the same as a confirmed zero
  confirmed_closing numeric,
  ann13_category    text,           -- see js/salesPurchaseBookConfirm.js; NULL = the
                                    -- section's default (Sales -> GoodSales,
                                    -- Purchase -> GoodPurchaseOthers)
  remarks           text,

  updated_by        text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),

  unique (book_id, section, party_key)
);

comment on table public.autobooks_parties is
  'Autobooks confirmation ledger — the figures a human types against a party (opening balance, as-per-confirmation taxable, closing balance, Annexure-13 category). Book figures are computed from autobooks_entries, never stored here.';

drop trigger if exists autobooks_parties_set_updated_at on public.autobooks_parties;
create trigger autobooks_parties_set_updated_at
  before update on public.autobooks_parties
  for each row execute function public.set_updated_at();

-- ── 4. Reconciliation statement adjustment lines ─────────────────────
create table if not exists public.autobooks_adjustments (
  id          bigint generated by default as identity primary key,
  book_id     bigint not null references public.autobooks_books(id) on delete cascade,
  statement   text   not null check (statement in ('sales', 'purchase', 'vat')),
  direction   text   not null check (direction in ('add', 'less')),
  -- Deliberately free text and a plain amount: the firm's own Reco sheet
  -- names a specific month's miscalculation ("Calculation Mistake of Taxable
  -- Sales in month of Ashad in Masebari"), and which mistakes exist varies
  -- per client and per year. Nothing here is hardcoded to a month.
  description text   not null default '',
  amount      numeric not null default 0,
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now()
);

comment on table public.autobooks_adjustments is
  'Ad-hoc add/less lines on an Autobooks reconciliation statement (Sales/Purchase/VAT). Free text on purpose — the adjustments differ per client and year.';

create index if not exists autobooks_adjustments_book_idx
  on public.autobooks_adjustments (book_id, statement, sort_order);

-- ── RLS: full member CRUD on all four ────────────────────────────────
alter table public.autobooks_books       enable row level security;
alter table public.autobooks_entries     enable row level security;
alter table public.autobooks_parties     enable row level security;
alter table public.autobooks_adjustments enable row level security;

do $$
declare t text;
begin
  foreach t in array array['autobooks_books', 'autobooks_entries', 'autobooks_parties', 'autobooks_adjustments'] loop
    execute format('drop policy if exists %I on public.%I', t || '_select_member', t);
    execute format('create policy %I on public.%I for select to authenticated using (private.is_app_user())', t || '_select_member', t);

    execute format('drop policy if exists %I on public.%I', t || '_insert_member', t);
    execute format('create policy %I on public.%I for insert to authenticated with check (private.is_app_user())', t || '_insert_member', t);

    execute format('drop policy if exists %I on public.%I', t || '_update_member', t);
    execute format('create policy %I on public.%I for update to authenticated using (private.is_app_user()) with check (private.is_app_user())', t || '_update_member', t);

    execute format('drop policy if exists %I on public.%I', t || '_delete_member', t);
    execute format('create policy %I on public.%I for delete to authenticated using (private.is_app_user())', t || '_delete_member', t);
  end loop;
end $$;
