-- ════════════════════════════════════════════════════════════════════
--  SERVICE MEMO FEE SKIPS (2026-08-15)
--
--  Backs the "Delete" action on Service Memo's Pending Memos list (§5.13).
--  That list is DERIVED (from audit_report_finalization and
--  projection_reports, never stored twice — see smFeeDueRows() in
--  js/serviceMemo.js), so there is no row to delete when a client's
--  reminder isn't wanted. This table records that a specific
--  (client, fiscal year, kind) reminder was deliberately dismissed, so
--  smFeeDueRows() can exclude it going forward — the derived list stays
--  derived, this just adds one more exclusion alongside "a matching memo
--  already exists".
--
--  · client_id      nullable FK — a typed-only projection (no directory
--                   client) can still be dismissed; matched on client_name
--                   instead, same fallback smFeeDueRows() already uses.
--  · fy_start_year  the NORMALIZED B.S. start year (NepaliLocale.fyStartYear()),
--                   not the raw string — ARF's fiscal_year is slash format
--                   and projection_reports' is dash, so comparing the
--                   normalized year is what keeps this join correct
--                   (CLAUDE.md §8).
--  · kind           'audit' | 'projection' — which source the reminder
--                   came from; the same client+year can have one skip per
--                   kind since they're unrelated reminders.
--
--  No UPDATE policy — a skip is created or deleted, never edited.
--
--  RLS: members (app_users) get full CRUD, mirroring service_memos /
--  projection_reports. New table => policies added in this same
--  migration or the app can't read it at all (§6.6).
--
--  Rollback: db/2026-08-15_service_memo_fee_skips_rollback.sql
-- ════════════════════════════════════════════════════════════════════

create table if not exists public.service_memo_fee_skips (
  id             bigint generated by default as identity primary key,
  client_id      bigint references public.clients(id) on delete cascade,
  client_name    text   not null,
  fy_start_year  int    not null,
  kind           text   not null check (kind in ('audit', 'projection')),
  dismissed_by   text,
  created_at     timestamptz not null default now()
);

comment on table public.service_memo_fee_skips is
  'Dismissed entries from Service Memo''s Pending Memos list — excludes a specific (client, fiscal year, kind) reminder derived from audit_report_finalization or projection_reports.';

create index if not exists service_memo_fee_skips_lookup_idx
  on public.service_memo_fee_skips (kind, fy_start_year, client_id);

-- ── RLS: full member CRUD (no update — a skip is created or deleted, never edited). ──
alter table public.service_memo_fee_skips enable row level security;

drop policy if exists service_memo_fee_skips_select_member on public.service_memo_fee_skips;
create policy service_memo_fee_skips_select_member on public.service_memo_fee_skips
  for select to authenticated using (private.is_app_user());

drop policy if exists service_memo_fee_skips_insert_member on public.service_memo_fee_skips;
create policy service_memo_fee_skips_insert_member on public.service_memo_fee_skips
  for insert to authenticated with check (private.is_app_user());

drop policy if exists service_memo_fee_skips_delete_member on public.service_memo_fee_skips;
create policy service_memo_fee_skips_delete_member on public.service_memo_fee_skips
  for delete to authenticated using (private.is_app_user());
