-- ════════════════════════════════════════════════════════════════════
--  FINANCIAL MANAGEMENT SUITE — Party Ledger + Final Account (2026-07-26)
--
--  Backs the department head's "Work Performed" workbook, which specifies
--  the four Financial Management screens as ONE connected ledger system
--  rather than four independent forms:
--
--    Service Memo (fee)          ─┐
--    Bank · Tax Payment (client) ─┼─▶ PARTY LEDGER ─▶ Total Receivables ─┐
--    Bank · Fee Receipt / For Tax ┘                                       │
--    Bank · Expenses ─▶ Expenses Ledger / Name List ───────────────────── ┼─▶ FINAL
--    Bank · Sapati   ─▶ Total Sapati ──────────────────────────────────── ┤   ACCOUNT
--    Bank accounts (by firm) ─▶ Bank Balance ───────────────────────────  ┘
--
--  Four changes, in the order they appear below:
--
--  1. service_memos loses its payment tracking. The workbook's service-memo
--     sheet is Date/PAN/Name/Address/Firm/Nature/Sub-Category/Description/
--     F.Y./Fee — nothing more. Collection is now recorded ONCE, as a bank
--     Fee Receipt, and netted in the Party Ledger; keeping a second copy on
--     the memo would let the two disagree. Verified before writing this:
--     5 memo rows exist and none has amount_received <> 0, so no data is
--     lost. `firm_other` backs the sheet's "other--Specify" firm option.
--
--  2. bank_accounts gains firm_key — column A ("Firms") of the sheet's
--     accounts table. This is what lets Final Account split Bank Balance
--     per firm. Nullable because the existing row predates it; the UI
--     requires it on every new/edited account. No is_cash flag: the sheet's
--     "Cash Balance Display in Dallakoti & Co" is just an account row named
--     e.g. "Cash in Hand" belonging to that firm.
--
--  3. bank_transactions gains two particulars the sheet marks "to be add":
--     `for_tax`     (receipt) — money taken from a client earmarked for tax
--     `tax_payment` (payment) — tax the firm paid on a client's behalf
--     Both carry client_id + counterparty_name exactly like fee_receipt, and
--     both land in the Party Ledger: for_tax on the "Less: Payment" side,
--     tax_payment on the "Total Tax Payment" side (it increases what the
--     client owes).
--
--  4. party_opening_balances backs the sheet's "Opening Balance / as on
--     01.04.2083 / Save" control — the one figure in the Party Ledger that
--     can't be derived from memos and bank rows. Everything else in that
--     ledger (net payable, party balances, receivables) stays derived at
--     read time, never stored (same discipline as billing overdue, §16).
--
--  RLS: new table gets the four private.is_app_user() member-CRUD policies,
--  or the app can't read it at all (§6.6). Altered tables keep theirs.
--
--  Rollback: db/2026-07-26_financial_suite_rollback.sql
-- ════════════════════════════════════════════════════════════════════

-- ── 1. service_memos: drop payment tracking, add "other" firm ────────
drop index if exists public.service_memos_status_idx;

alter table public.service_memos
  drop column if exists payment_status,
  drop column if exists amount_received,
  drop column if exists payment_date;

alter table public.service_memos
  add column if not exists firm_other text;   -- free text when firm_key = 'other'

comment on column public.service_memos.firm_other is
  'Firm name typed by the user when firm_key = ''other'' (the sheet''s "other--Specify" option).';

-- ── 2. bank_accounts: which firm owns the account ────────────────────
alter table public.bank_accounts
  add column if not exists firm_key text;     -- SERVICE_MEMO_FIRMS key (shailesh/dallakoti/rosp/rtc)

comment on column public.bank_accounts.firm_key is
  'Owning firm (js/config.js SERVICE_MEMO_FIRMS key). Drives Final Account''s per-firm Bank Balance.';

create index if not exists bank_accounts_firm_idx on public.bank_accounts (firm_key);

-- ── 3. bank_transactions: two new particulars ────────────────────────
alter table public.bank_transactions
  drop constraint if exists bank_transactions_particular_check;

alter table public.bank_transactions
  add constraint bank_transactions_particular_check
  check (particular in ('fee_receipt', 'for_tax', 'expenses', 'tax_payment', 'sapati', 'inter_bank_transfer'));

-- ── 4. party_opening_balances ────────────────────────────────────────
create table if not exists public.party_opening_balances (
  id             bigint generated by default as identity primary key,
  client_id      bigint not null references public.clients(id) on delete cascade,
  firm_key       text   not null,                  -- ledger is kept per firm
  fiscal_year    text   not null,                  -- dash format, e.g. '2083-84'
  as_on_date     text,                             -- B.S. 'YYYY.MM.DD' the opening is "as on"
  opening_amount numeric(16,2) not null default 0,
  client_name    text,                             -- snapshot (log-table discipline, §6.3)
  created_by     text,
  updated_by     text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  unique (client_id, firm_key, fiscal_year)
);

comment on table public.party_opening_balances is
  'Per-client opening balance for the Party Ledger. The only figure in that ledger that is stored rather than derived.';

create index if not exists party_opening_balances_client_idx on public.party_opening_balances (client_id);
create index if not exists party_opening_balances_firm_idx   on public.party_opening_balances (firm_key);
create index if not exists party_opening_balances_fy_idx     on public.party_opening_balances (fiscal_year);

drop trigger if exists set_party_opening_balances_updated_at on public.party_opening_balances;
create trigger set_party_opening_balances_updated_at
  before update on public.party_opening_balances
  for each row execute function public.set_updated_at();

-- ── RLS: full member CRUD. Non-members / anon get zero rows. ─────────
alter table public.party_opening_balances enable row level security;

drop policy if exists party_opening_balances_select_member on public.party_opening_balances;
create policy party_opening_balances_select_member on public.party_opening_balances
  for select to authenticated using (private.is_app_user());

drop policy if exists party_opening_balances_insert_member on public.party_opening_balances;
create policy party_opening_balances_insert_member on public.party_opening_balances
  for insert to authenticated with check (private.is_app_user());

drop policy if exists party_opening_balances_update_member on public.party_opening_balances;
create policy party_opening_balances_update_member on public.party_opening_balances
  for update to authenticated using (private.is_app_user()) with check (private.is_app_user());

drop policy if exists party_opening_balances_delete_member on public.party_opening_balances;
create policy party_opening_balances_delete_member on public.party_opening_balances
  for delete to authenticated using (private.is_app_user());
