-- ════════════════════════════════════════════════════════════════════
--  WORK TO-DO LIST — the third view inside Work Done  (2026-08-17)
--
--  Backs the new "To-Do List" section beside Work Records and Pending List
--  (js/workDoneTodo.js). The other two views answer questions about work the
--  firm has ALREADY committed to a record: Work Records is one page per
--  client per fiscal year, and the Pending List is a derived join over
--  document_register. Neither can hold "ring the client about the missing
--  Falgun bills before Thursday" — a short-lived, free-typed task that may
--  not map onto a catalogue work type and may not belong to a fiscal year at
--  all. That is what this table is for, and it is why it is a table of its
--  own rather than more rows inside work_done.items.
--
--  · ONE ROW PER TASK. No UNIQUE constraint and no (client, year) grain —
--    the same client can legitimately have six open to-dos at once, which is
--    exactly the case work_done's UNIQUE (client_id, fiscal_year) forbids.
--
--  · client_id is NULLABLE, ON DELETE SET NULL — deliberately unlike
--    work_done / audit_checklists / audit_report_finalization, which are all
--    NOT NULL + RESTRICT. A to-do is routinely internal ("renew the office
--    firm registration") or against a walk-in the directory doesn't carry
--    yet, and refusing to record it would send staff back to paper for
--    precisely the tasks most likely to be forgotten. client_name is
--    snapshotted alongside, so a to-do still reads after its client row is
--    gone — which is also why SET NULL is safe here where RESTRICT is right
--    for the record tables.
--
--  · nature_of_work is FREE TEXT, not a key into window.WD_WORK_TYPES.
--    The user asked to type it. The UI still offers the 16 catalogue labels
--    plus every value already used, through a datalist — the bbPopulateExpense
--    Names idiom, which keeps the vocabulary from fragmenting on near-
--    duplicate spellings without closing the field. A CHECK here would defeat
--    the point of the field.
--
--  · status IS STORED HERE, and that does NOT contradict the "status is
--    always derived" rule the neighbouring modules follow. Those modules
--    derive because the underlying facts already exist elsewhere (items[].
--    state, submission columns, doc_types vs outtakes) and a stored copy
--    could drift from them. A to-do has no underlying fact to derive from —
--    its state IS the record. The three keys match window.WD_STATES exactly
--    so the firm reads one vocabulary across all three views.
--
--  · completed_at is stamped when status becomes 'done' and CLEARED when it
--    moves back off — the same discipline as work_done items[].done_date. A
--    stale completion stamp on a reopened task misreports the work. Enforced
--    by the CHECK below rather than trusted to the client: this is the one
--    invariant the whole "Completed" section keys off.
--
--  · due_date is nullable on purpose. "Someday" is a real category and a
--    to-do list that forces a date gets fake dates typed into it, which is
--    worse than none — the UI shows undated tasks in their own section
--    rather than hiding them or treating them as overdue.
--
--  · No fiscal_year column. Every neighbouring module is fiscal-year grained;
--    a to-do is pinned to a date, not a year, and adding the field would put
--    a control on the quick-add bar that nothing reads. If the firm later
--    wants to tie to-dos to a year it is one nullable column and no data
--    migration.
--
--  RLS: standard member-CRUD (private.is_app_user()) on all 4 operations,
--  matching work_done — this is not firm_bank_details-sensitive data.
--
--  Rollback: db/2026-08-17_work_todos_rollback.sql
-- ════════════════════════════════════════════════════════════════════

create table if not exists public.work_todos (
  id                bigint generated by default as identity primary key,

  -- The "auto comes as today" date the task was written down. Editable, and
  -- separate from the immutable created_at for the same reason
  -- work_done.recorded_date is: staff routinely log on Monday a task they
  -- actually took on Friday, and the From/To filter has to follow the work.
  task_date         date        not null default current_date,

  client_id         bigint      references public.clients(id) on delete set null,
  client_name       text,                                   -- snapshot / free text
  client_pan        text,                                   -- snapshot

  nature_of_work    text        not null,
  remarks           text,

  status            text        not null default 'not_started'
                      constraint work_todos_status_chk
                      check (status in ('not_started', 'in_progress', 'done')),

  priority          text        not null default 'normal'
                      constraint work_todos_priority_chk
                      check (priority in ('low', 'normal', 'high')),

  -- A name from window.ARF_STAFF, or the name typed through its "Other"
  -- option replacing the literal 'Other' — the same convention as
  -- work_done.items[].staff and audit_report_finalization.auditor, so there
  -- is no separate *_other column anywhere.
  assigned_to       text,

  due_date          date,
  completed_at      timestamptz,

  created_by        text,
  updated_by        text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),

  -- Done ⇔ stamped. Neither a done task without a completion time nor a
  -- reopened task still carrying one can exist.
  constraint work_todos_completed_chk
    check ((status = 'done') = (completed_at is not null))
);

comment on table public.work_todos is
  'Free-form task list for the firm (Work Done → To-Do List view). One row per task, unlike work_done''s one row per client+fiscal year. client_id is nullable so internal and walk-in tasks can be recorded; nature_of_work is free text with a UI datalist. status is stored (not derived) because a to-do has no underlying fact to derive from, and completed_at is CHECK-tied to it.';

-- Sorted-list access path: the default view is "everything not done, soonest
-- due first", which is exactly this index.
create index if not exists wt_open_due_idx    on public.work_todos (status, due_date) where status <> 'done';
create index if not exists wt_client_idx      on public.work_todos (client_id);
create index if not exists wt_task_date_idx   on public.work_todos (task_date desc);
create index if not exists wt_assigned_to_idx on public.work_todos (assigned_to);

-- ── updated_at maintenance (reuses the shared trigger fn) ──
drop trigger if exists set_wt_updated_at on public.work_todos;
create trigger set_wt_updated_at
  before update on public.work_todos
  for each row execute function public.set_updated_at();

-- ── RLS: full member CRUD. Non-members / anon get zero rows. ──
alter table public.work_todos enable row level security;

drop policy if exists wt_select_member on public.work_todos;
create policy wt_select_member on public.work_todos
  for select to authenticated using (private.is_app_user());

drop policy if exists wt_insert_member on public.work_todos;
create policy wt_insert_member on public.work_todos
  for insert to authenticated with check (private.is_app_user());

drop policy if exists wt_update_member on public.work_todos;
create policy wt_update_member on public.work_todos
  for update to authenticated using (private.is_app_user()) with check (private.is_app_user());

drop policy if exists wt_delete_member on public.work_todos;
create policy wt_delete_member on public.work_todos
  for delete to authenticated using (private.is_app_user());
