-- ════════════════════════════════════════════════════════════════════
--  AUDIT CHECKLIST — pre-finalization QC sign-off sheet
--  (2026-08-09)
--
--  Backs the new "Audit Checklist" sidebar module (own top-level nav item,
--  next to Audit Report Finalization). Digitizes the paper QC sheet staff
--  fill per client/year before an audit report is finalized: a fixed list
--  of checklist items (P.Y figures tallied, bank balances, annexures, etc.)
--  each ticked off and attributed to whoever checked it, plus any number of
--  ad-hoc custom items.
--
--  · ONE ROW per (client_id, fiscal_year) — one QC pass per client per year,
--    not split by track like audit_report_finalization. Enforced by the
--    UNIQUE constraint below; js/auditChecklist.js detects an existing
--    (client, FY) row the moment both are picked and routes into edit mode
--    against it, so INSERT never collides with this constraint in normal
--    use.
--  · client_id is NOT NULL, ON DELETE RESTRICT — directory clients only (no
--    walk-in case like document_register), same posture as
--    audit_report_finalization.
--  · items is a JSONB ARRAY, not one column per checklist item:
--      [{ "key": "py_fig", "label": "P.Y Fig", "checked": false,
--         "checked_by": "", "custom": false }, ...]
--    The fixed item list can grow without a migration, and user-added
--    custom items are inherently variable-shape — a fixed-column schema
--    would need a migration for either. checked_by holds a staff/firm name
--    from window.AQC_STAFF, or — when the UI's "Other" option is chosen —
--    the typed name directly (replacing the literal "Other"), so there is
--    no separate *_other column, matching audit_report_finalization's
--    auditor field.
--  · Two of the fixed items ("Sales/Purchase with VAT Return",
--    "P.Y VAT Adjustment") are VAT-only and are simply omitted from a new
--    record's items array when clients.vat_status !== 'active' — nothing
--    to model in the schema for that.
--  · Status (Not Started / In Progress / Complete) is DERIVED in JS from
--    items[].checked, never stored — there is deliberately no status
--    column, so the badge/filter/stat-card can't drift from the data they
--    are computed from (same principle as audit_report_finalization).
--  · recorded_date is the day the QC pass was actually done, separate from
--    the immutable created_at, and user-editable — same reasoning and
--    From/To range-filter use as audit_report_finalization.recorded_date.
--
--  RLS: standard member-CRUD (private.is_app_user()) on all 4 operations —
--  no admin-only carve-out (this isn't firm_bank_details-sensitive data).
--
--  Rollback: db/2026-08-09_audit_checklist_rollback.sql
-- ════════════════════════════════════════════════════════════════════

create table if not exists public.audit_checklists (
  id                    bigint generated by default as identity primary key,
  client_id             bigint not null references public.clients(id) on delete restrict,
  client_name           text   not null,                   -- snapshot at save time
  client_pan            text,                               -- snapshot

  fiscal_year           text   not null,                    -- slash format, e.g. '2082/83'
  recorded_date         date   not null default current_date,

  items                 jsonb  not null default '[]'::jsonb,

  remarks               text,
  created_by            text,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),

  constraint audit_checklists_client_fy_uniq unique (client_id, fiscal_year)
);

comment on table public.audit_checklists is
  'Per-client, per-fiscal-year QC checklist run before an audit report is finalized (Audit Checklist module). items is a jsonb array of {key,label,checked,checked_by,custom}.';

create index if not exists achk_client_idx        on public.audit_checklists (client_id);
create index if not exists achk_fiscal_year_idx   on public.audit_checklists (fiscal_year);
create index if not exists achk_recorded_date_idx on public.audit_checklists (recorded_date desc);

-- ── updated_at maintenance (reuses the shared trigger fn) ──
drop trigger if exists set_achk_updated_at on public.audit_checklists;
create trigger set_achk_updated_at
  before update on public.audit_checklists
  for each row execute function public.set_updated_at();

-- ── RLS: full member CRUD. Non-members / anon get zero rows. ──
alter table public.audit_checklists enable row level security;

drop policy if exists achk_select_member on public.audit_checklists;
create policy achk_select_member on public.audit_checklists
  for select to authenticated using (private.is_app_user());

drop policy if exists achk_insert_member on public.audit_checklists;
create policy achk_insert_member on public.audit_checklists
  for insert to authenticated with check (private.is_app_user());

drop policy if exists achk_update_member on public.audit_checklists;
create policy achk_update_member on public.audit_checklists
  for update to authenticated using (private.is_app_user()) with check (private.is_app_user());

drop policy if exists achk_delete_member on public.audit_checklists;
create policy achk_delete_member on public.audit_checklists
  for delete to authenticated using (private.is_app_user());
