-- ════════════════════════════════════════════════════════════════════
--  WORK DONE — what work has actually been finished, per client per year
--  (2026-08-09)
--
--  Backs the new "Work Done" sidebar module (between File In Out and Audit
--  Checklist in the firm's workflow). Digitizes the paper "Work done Module"
--  sheet: one client + fiscal year, then a fixed list of work types (Sales
--  Register, VAT Reco, Ann-13, Financial Statement, VAT Return, ETDS,
--  IRD Submission, ...), each carrying who did it, what state it's in, and
--  remarks. It exists because work is done in pieces by several people over
--  several days, and nothing recorded which pieces were finished — so work
--  got forgotten, redone, or started twice.
--
--  · ONE ROW per (client_id, fiscal_year) — the sheet is one page per client
--    per year. Enforced by the UNIQUE constraint below; js/workDone.js
--    detects an existing (client, FY) row the moment both are picked and
--    routes into edit mode against it, so INSERT never collides with this
--    constraint in normal use. Same grain and same auto-match idiom as
--    audit_checklists.
--  · client_id is NOT NULL, ON DELETE RESTRICT — directory clients only, no
--    walk-in case like document_register, same posture as audit_checklists
--    and audit_report_finalization.
--  · items is a JSONB ARRAY, not one column per work type:
--      [{ "key": "sales_register", "label": "Sales Register",
--         "state": "done", "staff": "Kesav", "remarks": "",
--         "done_date": "2026-08-09", "custom": false }, ...]
--    The fixed work-type list (window.WD_WORK_TYPES) can grow without a
--    migration, and user-added custom work rows are inherently
--    variable-shape — a fixed-column schema would need a migration for
--    either. `state` is one of not_started / in_progress / done; three
--    states rather than a plain done-tick because "I'm on it" is what stops
--    two staff starting the same job, which is half the reason the module
--    exists. `staff` holds a name from window.ARF_STAFF (reused, NOT copied
--    — same humans as Audit Report Finalization) or, when "Other" is chosen,
--    the typed name directly replacing the literal "Other", so there is no
--    separate *_other column — matching audit_report_finalization.auditor
--    and audit_checklists.items[].checked_by.
--  · Status (Not Started / In Progress / Complete) and progress are DERIVED
--    in JS from items[].state, never stored — there is deliberately no
--    status column, so the badge, the stat cards, the filter and the export
--    text can't drift from the data they're computed from (same principle as
--    audit_checklists and audit_report_finalization).
--  · THE PENDING LIST IS NOT STORED HERE AT ALL. The firm's sheet says three
--    work types (Sales Register, Purchase Register, Stock Book) show in a
--    pending list "if file is received and work is not done". Those three
--    labels are exactly three of the nine window.FM_DOC_TYPES that File In
--    Out already records against public.document_register, so the pending
--    list is computed as a join between that table and this one — never
--    hand-ticked, so it cannot go stale and nothing is entered twice. The
--    two tables' fiscal_year columns are in DIFFERENT formats on purpose
--    (document_register.fiscal_year is free text, dash style '2081-82';
--    this one is a dropdown, slash style '2082/83' — CLAUDE.md §8 keeps
--    per-module formats deliberately distinct), so the join normalizes both
--    through NepaliLocale.fyStartYear() rather than comparing strings. A
--    string equality join here would match nothing and fail SILENTLY.
--  · recorded_date is the day the work was actually logged, separate from
--    the immutable created_at and user-editable — same reasoning and
--    From/To range-filter use as audit_checklists.recorded_date and
--    audit_report_finalization.recorded_date.
--
--  RLS: standard member-CRUD (private.is_app_user()) on all 4 operations —
--  no admin-only carve-out (this isn't firm_bank_details-sensitive data).
--
--  Rollback: db/2026-08-09_work_done_rollback.sql
-- ════════════════════════════════════════════════════════════════════

create table if not exists public.work_done (
  id                    bigint generated by default as identity primary key,
  client_id             bigint not null references public.clients(id) on delete restrict,
  client_name           text   not null,                   -- snapshot at save time
  client_pan            text,                               -- snapshot

  fiscal_year           text   not null,                    -- slash format, e.g. '2082/83'
  recorded_date         date   not null default current_date,

  items                 jsonb  not null default '[]'::jsonb,

  remarks               text,
  created_by            text,
  updated_by            text,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),

  constraint work_done_client_fy_uniq unique (client_id, fiscal_year)
);

comment on table public.work_done is
  'Per-client, per-fiscal-year record of which pieces of work have actually been finished (Work Done module). items is a jsonb array of {key,label,state,staff,remarks,done_date,custom}; state is not_started/in_progress/done. Status is derived in JS, never stored. The module''s Pending List is a join against public.document_register, not a column here.';

create index if not exists wd_client_idx        on public.work_done (client_id);
create index if not exists wd_fiscal_year_idx   on public.work_done (fiscal_year);
create index if not exists wd_recorded_date_idx on public.work_done (recorded_date desc);

-- ── updated_at maintenance (reuses the shared trigger fn) ──
drop trigger if exists set_wd_updated_at on public.work_done;
create trigger set_wd_updated_at
  before update on public.work_done
  for each row execute function public.set_updated_at();

-- ── RLS: full member CRUD. Non-members / anon get zero rows. ──
alter table public.work_done enable row level security;

drop policy if exists wd_select_member on public.work_done;
create policy wd_select_member on public.work_done
  for select to authenticated using (private.is_app_user());

drop policy if exists wd_insert_member on public.work_done;
create policy wd_insert_member on public.work_done
  for insert to authenticated with check (private.is_app_user());

drop policy if exists wd_update_member on public.work_done;
create policy wd_update_member on public.work_done
  for update to authenticated using (private.is_app_user()) with check (private.is_app_user());

drop policy if exists wd_delete_member on public.work_done;
create policy wd_delete_member on public.work_done
  for delete to authenticated using (private.is_app_user());
