-- ════════════════════════════════════════════════════════════════════
--  SERVICE MEMOS — internal service record + fee tracking (2026-07-21)
--
--  Backs the Service Memo module. A Service Memo is an INTERNAL record
--  that a piece of professional work was done for a client and what fee
--  is to be collected — deliberately NOT an accounting/tax invoice (that
--  is the separate `invoices` table / Billing module, which carries bank
--  details, a payment QR and a payments subtable). A memo is therefore a
--  single row: one Fee, one optional VAT line, and a single amount_received
--  for lightweight payment tracking. No line-item or payments subtable.
--
--  · firm_key / memo_prefix  the four selectable firms live only in JS
--                            config (window.SERVICE_MEMO_FIRMS). The app
--                            sends memo_prefix on insert (e.g. 'SM-SA',
--                            'SM-DC', 'SM-ROSP', 'SM-RTC') so the number
--                            trigger stays firm-list-agnostic — a new firm
--                            needs no migration.
--  · memo_number             assigned by an AFTER INSERT trigger, mirroring
--                            public.set_invoice_number: prefix || '-' ||
--                            lpad(id, 5, '0')  ->  e.g. 'SM-SA-00001'.
--  · payment_status          pending / partially_paid / paid. Defaults
--                            pending; the UI derives it from amount_received
--                            but it stays editable. balance_due is derived
--                            in JS (total_amount - amount_received), never
--                            stored (same discipline as billing overdue).
--  · client_id               nullable FK — a memo for a manually-typed
--                            client (not yet in the directory) still saves;
--                            name/pan/address are snapshotted regardless.
--
--  RLS: members (app_users) get full CRUD — working data, mirroring
--  vat_filings / depreciation_schedules. New table => policies added here,
--  or the app can't read it at all (§6.6). Uses private.is_app_user().
--
--  Rollback: db/2026-07-21_service_memos_rollback.sql
-- ════════════════════════════════════════════════════════════════════

create table if not exists public.service_memos (
  id                bigint generated by default as identity primary key,
  memo_number       text,                              -- trigger-assigned
  memo_prefix       text   not null,                   -- from SERVICE_MEMO_FIRMS
  firm_key          text   not null,
  memo_date         date   not null default current_date,
  client_id         bigint references public.clients(id) on delete set null,
  client_name       text   not null,                   -- snapshot at save time
  client_pan        text,                              -- snapshot
  client_address    text,                              -- snapshot
  nature_category   text   not null,
  nature_subcategory text,
  nature_other      text,                              -- free text when "others"
  description       text,
  fiscal_year       text,                              -- dash format, e.g. '2081-82'
  professional_fee  numeric(14,2) not null default 0,
  apply_vat         boolean not null default false,
  vat_amount        numeric(14,2) not null default 0,
  total_amount      numeric(14,2) not null default 0,
  payment_status    text   not null default 'pending'
                    check (payment_status in ('pending', 'partially_paid', 'paid')),
  amount_received   numeric(14,2) not null default 0,
  payment_date      date,
  remarks           text,
  created_by        text,
  updated_by        text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

comment on table public.service_memos is
  'Internal service records + fee tracking (Service Memo module). Not a tax invoice — see public.invoices for accounting invoices.';

create index if not exists service_memos_client_idx  on public.service_memos (client_id);
create index if not exists service_memos_firm_idx    on public.service_memos (firm_key);
create index if not exists service_memos_status_idx  on public.service_memos (payment_status);
create index if not exists service_memos_created_idx on public.service_memos (created_at desc);

-- ── Auto memo number (AFTER INSERT, mirrors public.set_invoice_number) ──
create or replace function public.set_service_memo_number()
  returns trigger
  language plpgsql
  set search_path to ''
as $function$
begin
  if new.memo_number is null then
    update public.service_memos
      set memo_number = coalesce(new.memo_prefix, 'SM') || '-' || lpad(new.id::text, 5, '0')
      where id = new.id;
  end if;
  return null;
end $function$;

drop trigger if exists set_service_memo_number on public.service_memos;
create trigger set_service_memo_number
  after insert on public.service_memos
  for each row execute function public.set_service_memo_number();

-- ── updated_at maintenance (reuses the shared trigger fn) ──
drop trigger if exists set_service_memos_updated_at on public.service_memos;
create trigger set_service_memos_updated_at
  before update on public.service_memos
  for each row execute function public.set_updated_at();

-- ── RLS: full member CRUD. Non-members / anon get zero rows. ──
alter table public.service_memos enable row level security;

drop policy if exists service_memos_select_member on public.service_memos;
create policy service_memos_select_member on public.service_memos
  for select to authenticated using (private.is_app_user());

drop policy if exists service_memos_insert_member on public.service_memos;
create policy service_memos_insert_member on public.service_memos
  for insert to authenticated with check (private.is_app_user());

drop policy if exists service_memos_update_member on public.service_memos;
create policy service_memos_update_member on public.service_memos
  for update to authenticated using (private.is_app_user()) with check (private.is_app_user());

drop policy if exists service_memos_delete_member on public.service_memos;
create policy service_memos_delete_member on public.service_memos
  for delete to authenticated using (private.is_app_user());
