-- ════════════════════════════════════════════════════════════════════
--  AUDIT REPORT FINALIZATION — IT/Estimate return & tax clearance tracker
--  (2026-08-09)
--
--  Backs the new "Audit Report Finalization" sidebar module (own top-level
--  nav item, NOT tied to document generation — a shared status tracker used
--  by multiple staff to record where a client's IT return / estimate return
--  submission and tax clearance stand for a fiscal year).
--
--  · ONE EVOLVING ROW per (client_id, fiscal_year) — staff edit the same
--    record over time as the picture changes, never a new row per edit.
--    Enforced by the UNIQUE constraint below. js/auditReportFinalization.js
--    detects an existing (client, FY) row the moment both are picked in the
--    form and routes into edit mode against it, so INSERT never collides
--    with this constraint in normal use.
--  · client_id is NOT NULL, ON DELETE RESTRICT — this module tracks
--    directory clients only (no walk-ins, unlike document_register), and
--    deleting a client with tracking history should fail loudly rather than
--    silently lose it.
--  · it_verified / estimate_verified are NULLABLE booleans: null = not yet
--    reviewed, true = verified, false = not verified. The 4-key DISPLAY
--    status (not_submitted / submitted / verified / not_verified) shown in
--    the UI is DERIVED in JS (arfItStatusKey / arfEstimateStatusKey in
--    js/auditReportFinalization.js) from these columns plus the
--    submission-no / checked-by text fields — there is deliberately no
--    stored status column for either track, so the badge can't drift from
--    the fields it's computed from.
--  · it_entered_by / estimate_checked_by hold the final staff name — when
--    the UI's "Other" option is chosen, the typed name is written directly
--    into this column (replacing the literal "Other"), so there is no
--    separate *_other column for either field.
--  · tax_clearance is a plain NOT NULL boolean (2-state, default false) —
--    unlike the two verified flags, there is no tri-state "not reviewed"
--    need here (confirmed: "yes or no, if yes then a date").
--  · No register-number trigger (no FM-00001-style ref) — this module has
--    no natural "reference number" concept; the bigint id is enough.
--
--  RLS: standard member-CRUD (private.is_app_user()) on all 4 operations —
--  no admin-only carve-out (this isn't firm_bank_details-sensitive data).
--
--  Rollback: db/2026-08-09_audit_report_finalization_rollback.sql
-- ════════════════════════════════════════════════════════════════════

create table if not exists public.audit_report_finalization (
  id                    bigint generated by default as identity primary key,
  client_id             bigint not null references public.clients(id) on delete restrict,
  client_name           text   not null,                   -- snapshot at save time
  client_pan            text,                               -- snapshot

  fiscal_year           text   not null,                    -- slash format, e.g. '2083/84'
  auditor               text   not null
                        check (auditor in ('Shailesh Dallakoti', 'Non-Sign', 'Devi Prasad Dallakoti', 'Lila Adhikari', 'Surya Poudel')),

  -- IT Return block
  it_entered_by         text,                                -- staff name, or the typed "Other" name
  it_submission_no      text,
  it_verified           boolean,                             -- null = not yet reviewed

  -- Estimate Return block (mirrors IT Return's shape)
  estimate_checked_by   text,
  estimate_verified     boolean,                             -- null = not yet reviewed

  -- Tax Clearance — 2-state only, unlike the two verified flags above
  tax_clearance          boolean not null default false,
  tax_clearance_date     date,

  remarks                text,
  created_by             text,
  updated_by             text,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),

  constraint audit_report_finalization_client_fy_uniq unique (client_id, fiscal_year)
);

comment on table public.audit_report_finalization is
  'Per-client, per-fiscal-year tracker for IT return / Estimate return submission & tax clearance status (Audit Report Finalization module).';

create index if not exists arf_client_idx      on public.audit_report_finalization (client_id);
create index if not exists arf_fiscal_year_idx on public.audit_report_finalization (fiscal_year);
create index if not exists arf_auditor_idx     on public.audit_report_finalization (auditor);

-- ── updated_at maintenance (reuses the shared trigger fn) ──
drop trigger if exists set_arf_updated_at on public.audit_report_finalization;
create trigger set_arf_updated_at
  before update on public.audit_report_finalization
  for each row execute function public.set_updated_at();

-- ── RLS: full member CRUD. Non-members / anon get zero rows. ──
alter table public.audit_report_finalization enable row level security;

drop policy if exists arf_select_member on public.audit_report_finalization;
create policy arf_select_member on public.audit_report_finalization
  for select to authenticated using (private.is_app_user());

drop policy if exists arf_insert_member on public.audit_report_finalization;
create policy arf_insert_member on public.audit_report_finalization
  for insert to authenticated with check (private.is_app_user());

drop policy if exists arf_update_member on public.audit_report_finalization;
create policy arf_update_member on public.audit_report_finalization
  for update to authenticated using (private.is_app_user()) with check (private.is_app_user());

drop policy if exists arf_delete_member on public.audit_report_finalization;
create policy arf_delete_member on public.audit_report_finalization
  for delete to authenticated using (private.is_app_user());
