-- ════════════════════════════════════════════════════════════════════
--  DEPRECIATION — persistence + year-over-year carry-forward (2026-07-17)
--
--  Backs the Depreciation module's new "save & carry forward" feature: a
--  saved schedule for (client, scheme, fiscal_year) lets the NEXT year's
--  sheet auto-fill each pool's Opening from this year's closing WDV.
--
--  · scheme          'normal'  = Depreciation as per Income Tax
--                    'special' = Special Industries (accelerated rates)
--  · pools           jsonb array of per-pool inputs + computed closing WDV;
--                    the closing WDV is what next year reads as Opening.
--  · addition_details jsonb array of the itemized purchase helper lines.
--
--  Saving is MANUAL (a Save button in the UI) — generating the Excel never
--  writes here, so the user can test freely. One row per
--  (client_id, scheme, fiscal_year); re-saving upserts.
--
--  RLS: members (app_users) get full CRUD — this is working data, mirroring
--  vat_filings. New table => policies added here, or the app can't read it
--  (§6.6). Follows the private.is_app_user() membership pattern.
--
--  Rollback: db/2026-07-17_depreciation_schedules_rollback.sql
-- ════════════════════════════════════════════════════════════════════

create table if not exists public.depreciation_schedules (
  id                bigint generated by default as identity primary key,
  client_id         bigint not null references public.clients(id) on delete cascade,
  scheme            text   not null default 'normal' check (scheme in ('normal', 'special')),
  fiscal_year       text   not null,                 -- dash format, e.g. '2081-82'
  company_name      text,                            -- snapshot at save time
  pan               text,                            -- snapshot at save time
  pools             jsonb  not null default '[]'::jsonb,
  addition_details  jsonb  not null default '[]'::jsonb,
  created_by        text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (client_id, scheme, fiscal_year)
);

comment on table public.depreciation_schedules is
  'Saved depreciation working per (client, scheme, fiscal_year); closing WDV in pools carries forward to next year''s Opening. Manual save from the Depreciation module.';

create index if not exists depreciation_schedules_client_scheme_idx
  on public.depreciation_schedules (client_id, scheme, fiscal_year);

-- updated_at maintenance (reuses the shared trigger fn)
drop trigger if exists set_depreciation_schedules_updated_at on public.depreciation_schedules;
create trigger set_depreciation_schedules_updated_at
  before update on public.depreciation_schedules
  for each row execute function public.set_updated_at();

-- ── RLS: full member CRUD (upsert needs INSERT + UPDATE; Delete button
--    needs DELETE). Non-members / anon get zero rows. ──
alter table public.depreciation_schedules enable row level security;

drop policy if exists depreciation_schedules_select_member on public.depreciation_schedules;
create policy depreciation_schedules_select_member on public.depreciation_schedules
  for select to authenticated using (private.is_app_user());

drop policy if exists depreciation_schedules_insert_member on public.depreciation_schedules;
create policy depreciation_schedules_insert_member on public.depreciation_schedules
  for insert to authenticated with check (private.is_app_user());

drop policy if exists depreciation_schedules_update_member on public.depreciation_schedules;
create policy depreciation_schedules_update_member on public.depreciation_schedules
  for update to authenticated using (private.is_app_user()) with check (private.is_app_user());

drop policy if exists depreciation_schedules_delete_member on public.depreciation_schedules;
create policy depreciation_schedules_delete_member on public.depreciation_schedules
  for delete to authenticated using (private.is_app_user());
