-- ════════════════════════════════════════════════════════════════════
--  ROLLBACK for db/2026-08-10_drop_vat_filings.sql
--
--  ⚠ THIS RESTORES THE STRUCTURE, NOT THE DATA. The 15 filing rows that
--  existed when the table was dropped are gone unless they were exported
--  or restored from a Supabase point-in-time backup first. Recreating the
--  table gives the module something to read again; it comes back empty,
--  and because rows are lazy (no row = "Not Started") an empty table is
--  indistinguishable from "nothing has been filed this year".
--
--  Column definitions, CHECKs and RLS policies below are reproduced from
--  the live schema as verified 2026-08-10 via the Supabase MCP, and match
--  db/2026-07-16_rls_lockdown.sql for the policy block.
--
--  Restoring the module itself also means bringing back js/vatCompliance.js,
--  its index.html panel/nav/modals, its .vatc-* CSS and its script tag —
--  all recoverable from git history (see the commit that added this file).
-- ════════════════════════════════════════════════════════════════════

create table if not exists public.vat_filings (
  id                 bigint generated by default as identity primary key,
  client_id          bigint not null references public.clients(id),
  fiscal_year        text   not null,
  month              smallint not null check (month >= 1 and month <= 12),
  status             text   not null default 'not_started'
                       check (status in ('not_started','waiting_docs','ocr_processing',
                                         'under_review','ready_to_file','filed',
                                         'filed_adjustments','on_hold','not_required')),
  status_changed_at  timestamptz not null default now(),
  filed_date_bs      text,
  filed_at           timestamptz,
  assigned_staff_id  bigint references public.app_users(id),
  notes              text,
  workbook_filename  text,
  pdf_filename       text,
  validation_summary jsonb,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  updated_by         text,
  unique (client_id, fiscal_year, month)
);

alter table public.vat_filings enable row level security;

-- Full member workflow (the module's upsert needs INSERT + UPDATE).
-- No delete policy — the UI never deleted filings.
drop policy if exists vat_filings_select_member on public.vat_filings;
create policy vat_filings_select_member on public.vat_filings
  for select to authenticated using (private.is_app_user());
drop policy if exists vat_filings_insert_member on public.vat_filings;
create policy vat_filings_insert_member on public.vat_filings
  for insert to authenticated with check (private.is_app_user());
drop policy if exists vat_filings_update_member on public.vat_filings;
create policy vat_filings_update_member on public.vat_filings
  for update to authenticated using (private.is_app_user()) with check (private.is_app_user());
