-- ════════════════════════════════════════════════════════════════════════════
--  ROLLBACK for 2026-08-18_drop_billing.sql
-- ════════════════════════════════════════════════════════════════════════════
--
--  ⚠  RESTORES STRUCTURE ONLY — NOT DATA.
--
--  Running this gives you four empty tables, the four functions and the RLS
--  policies back. It does not give you the 3 invoices, 5 line items, 1 payment
--  or 2 firm bank rows. Those live in:
--
--      db/backups/2026-08-18_billing_export.json   (gitignored)
--
--  Re-import them from that file AFTER running this, and remember the
--  sequences: invoices.id reached 9 and invoice_items.id reached 14, so a
--  restore must either preserve the ids and then advance the identity
--  sequences (`alter table … alter column id restart with 10`) or accept
--  renumbering. Restoring rows without advancing the sequence will collide on
--  the very next insert.
--
--  Restoring the schema alone is not enough to make the module work again:
--  js/billing.js, the panel and modals in index.html, the .billing-* CSS and
--  the MODULE_INITS entry were deleted in the same commit. Recover those from
--  git history first, then run this.
--
--  Reproduced verbatim from db/00_bootstrap.sql as it stood before the drop.
-- ════════════════════════════════════════════════════════════════════════════

begin;

-- ── Tables, parents first (invoices FKs firm_bank_details) ──────────────────

create table public.firm_bank_details (
  firm_key text primary key,
  invoice_prefix text not null,
  bank_name text,
  account_name text,
  account_number text,
  branch text,
  qr_image text,
  updated_at timestamptz not null default now(),
  updated_by text
);

create table public.invoices (
  id bigint generated by default as identity primary key,
  invoice_number text unique,
  client_id bigint not null references public.clients(id) on delete restrict,
  firm_key text not null references public.firm_bank_details(firm_key),
  issue_date date not null default current_date,
  due_date date,
  fiscal_year text,
  status text not null default 'draft',
  subtotal numeric(14,2) not null default 0,
  tax_rate numeric(5,4) not null default 0.13,
  tax_amount numeric(14,2) not null default 0,
  total_amount numeric(14,2) not null default 0,
  amount_paid numeric(14,2) not null default 0,
  notes text,
  pdf_filename text,
  created_at timestamptz not null default now(),
  created_by text,
  updated_at timestamptz not null default now(),
  updated_by text,
  constraint invoices_status_check
    check (status = any (array['draft','sent','partially_paid','paid','void']))
);

create table public.invoice_items (
  id bigint generated by default as identity primary key,
  invoice_id bigint not null references public.invoices(id) on delete cascade,
  description text not null,
  quantity numeric(10,2) not null default 1,
  rate numeric(14,2) not null default 0,
  amount numeric(14,2) not null default 0,
  sort_order integer not null default 0
);

create table public.invoice_payments (
  id bigint generated by default as identity primary key,
  invoice_id bigint not null references public.invoices(id) on delete restrict,
  client_id bigint not null references public.clients(id) on delete restrict,
  amount numeric(14,2) not null,
  paid_date date not null default current_date,
  method text not null default 'bank_transfer',
  note text,
  recorded_by text,
  created_at timestamptz not null default now(),
  constraint invoice_payments_amount_check check (amount > 0),
  constraint invoice_payments_method_check
    check (method = any (array['cash','bank_transfer','qr','cheque','other']))
);

-- ── Functions ───────────────────────────────────────────────────────────────

create or replace function public.set_invoice_number()
returns trigger language plpgsql set search_path to ''
as $function$
declare prefix text;
begin
  if new.invoice_number is null then
    select invoice_prefix into prefix from public.firm_bank_details where firm_key = new.firm_key;
    update public.invoices set invoice_number = coalesce(prefix, 'INV') || '-' || lpad(new.id::text, 5, '0')
      where id = new.id;
  end if;
  return null;
end $function$;

create or replace function public.sync_invoice_payment_totals()
returns trigger language plpgsql set search_path to ''
as $function$
declare
  v_invoice_id bigint := coalesce(new.invoice_id, old.invoice_id);
  v_total numeric(14,2);
  v_status text;
  v_paid numeric(14,2);
begin
  select total_amount, status into v_total, v_status from public.invoices where id = v_invoice_id;
  select coalesce(sum(amount), 0) into v_paid from public.invoice_payments where invoice_id = v_invoice_id;

  update public.invoices
    set amount_paid = v_paid,
        status = case
          when status = 'void' then status
          when v_paid <= 0 then case when status in ('paid','partially_paid') then 'sent' else status end
          when v_paid >= v_total and v_total > 0 then 'paid'
          else 'partially_paid'
        end
    where id = v_invoice_id;
  return null;
end $function$;

create or replace function public.get_billing_stats()
returns table(total_outstanding numeric, overdue_amount numeric, month_income numeric,
              invoices_sent_month bigint, draft_count bigint, paid_month_count bigint)
language sql stable set search_path to ''
as $function$
  select
    (select coalesce(sum(total_amount - amount_paid), 0) from public.invoices where status not in ('paid','void')),
    (select coalesce(sum(total_amount - amount_paid), 0) from public.invoices where status not in ('paid','void') and due_date < current_date),
    (select coalesce(sum(amount), 0) from public.invoice_payments where paid_date >= date_trunc('month', current_date)),
    (select count(*) from public.invoices where status <> 'draft' and created_at >= date_trunc('month', current_date)),
    (select count(*) from public.invoices where status = 'draft'),
    (select count(*) from public.invoices where status = 'paid' and updated_at >= date_trunc('month', current_date));
$function$;

create or replace function public.get_monthly_income(p_months integer default 6)
returns table(month_start date, total numeric)
language sql stable set search_path to ''
as $function$
  select date_trunc('month', paid_date)::date, sum(amount)
  from public.invoice_payments
  where paid_date >= date_trunc('month', current_date) - (p_months - 1) * interval '1 month'
  group by 1 order by 1;
$function$;

-- ── Indexes ─────────────────────────────────────────────────────────────────

create index invoice_items_invoice_idx   on public.invoice_items using btree (invoice_id);
create index invoice_payments_client_idx  on public.invoice_payments using btree (client_id);
create index invoice_payments_date_idx    on public.invoice_payments using btree (paid_date);
create index invoice_payments_invoice_idx on public.invoice_payments using btree (invoice_id);
create index invoices_client_idx   on public.invoices using btree (client_id);
create index invoices_due_date_idx on public.invoices using btree (due_date) where (status <> all (array['paid','void']));
create index invoices_status_idx   on public.invoices using btree (status);

-- ── Triggers ────────────────────────────────────────────────────────────────
-- set_updated_at() was never dropped; it is shared with 14 other triggers.

create trigger invoices_set_updated_at before update on public.invoices
  for each row execute function public.set_updated_at();
create trigger invoices_set_number after insert on public.invoices
  for each row execute function public.set_invoice_number();
create trigger invoice_payments_sync after insert or delete or update on public.invoice_payments
  for each row execute function public.sync_invoice_payment_totals();

-- ── Grants + RLS ────────────────────────────────────────────────────────────

grant all on table public.invoices, public.invoice_items,
                   public.invoice_payments, public.firm_bank_details
  to anon, authenticated, service_role;
grant execute on function public.get_billing_stats()         to authenticated, service_role;
grant execute on function public.get_monthly_income(integer) to authenticated, service_role;

alter table public.invoices          enable row level security;
alter table public.invoice_items     enable row level security;
alter table public.invoice_payments  enable row level security;
alter table public.firm_bank_details enable row level security;

create policy invoices_select_member on public.invoices for select to authenticated using (private.is_app_user());
create policy invoices_insert_member on public.invoices for insert to authenticated with check (private.is_app_user());
create policy invoices_update_member on public.invoices for update to authenticated using (private.is_app_user()) with check (private.is_app_user());
create policy invoices_delete_member on public.invoices for delete to authenticated using (private.is_app_user());

create policy invoice_items_select_member on public.invoice_items for select to authenticated using (private.is_app_user());
create policy invoice_items_insert_member on public.invoice_items for insert to authenticated with check (private.is_app_user());
create policy invoice_items_delete_member on public.invoice_items for delete to authenticated using (private.is_app_user());

-- No UPDATE/DELETE on payments, deliberately: a recorded payment drives the
-- invoice status trigger, so an editable payment could drift from the status.
create policy invoice_payments_select_member on public.invoice_payments for select to authenticated using (private.is_app_user());
create policy invoice_payments_insert_member on public.invoice_payments for insert to authenticated with check (private.is_app_user());

-- Writes admin-only: bank details + payment QR are the payment-fraud target.
create policy firm_bank_details_select_member on public.firm_bank_details for select to authenticated using (private.is_app_user());
create policy firm_bank_details_insert_admin  on public.firm_bank_details for insert to authenticated with check (private.is_admin());
create policy firm_bank_details_update_admin  on public.firm_bank_details for update to authenticated using (private.is_admin()) with check (private.is_admin());

commit;

-- get_vat_fy_stats() is deliberately NOT restored. It was already broken —
-- it reads public.vat_filings, dropped 2026-08-10 — so recreating it would
-- fail at CREATE time anyway (a LANGUAGE sql body is validated then).

-- Expect: billing_tables 4 | billing_functions 4 | policies 94
select
  (select count(*) from pg_class c join pg_namespace n on n.oid = c.relnamespace
     where n.nspname = 'public' and c.relkind = 'r'
       and c.relname in ('invoices','invoice_items','invoice_payments','firm_bank_details'))
                                                                   as billing_tables,
  (select count(*) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public'
       and p.proname in ('set_invoice_number','sync_invoice_payment_totals',
                         'get_billing_stats','get_monthly_income'))as billing_functions,
  (select count(*) from pg_policies where schemaname = 'public')   as policies;
