-- ════════════════════════════════════════════════════════════════════
--  FINANCIAL STATEMENTS — saved statement workings (2026-07-26)
--
--  Backs the Financial Statement module (§5.18). One row = one client's
--  full NFRS statement set for one fiscal year on one basis: the parsed
--  prior-year comparative, the summary figures A–N the accountant
--  entered, and the fully solved statements.
--
--  Saving `computed` makes a filed statement reproducible without
--  re-uploading the prior-year workbook, and gives next year's run a
--  carry-forward base — the same reasoning as projection_reports.
--
--  · client_id   nullable FK — a statement for a company not yet in the
--                directory still saves; name/pan snapshotted regardless.
--  · basis       'provisional' | 'audited'. This is NOT cosmetic: it
--                decides both the statement titles (a provisional set is
--                titled "Provisional Statement of …", except the
--                Statement of Changes in Equity which is never prefixed)
--                and what gets taxed — audited returns tax the taxable
--                profit, provisional returns tax the profit before tax.
--                A client legitimately has both for one year, which is
--                why it is part of the unique key.
--  · return_type 'D1' | 'D2' | 'D3' | 'D3V'. Free text, not a CHECK, for
--                the same reason clients.it_return_type is (§16) — the
--                firm's own vocabulary here is still settling.
--  · inputs      jsonb: { figures, levers, ppe, py, identity } —
--                everything needed to re-run FinStatementEngine.build()
--                and get byte-identical output.
--  · computed    jsonb: the build() output at the moment of saving —
--                statements, COI tax computation, proofs, issues.
--  · fiscal_year dash format, e.g. '2082-83'.
--
--  RLS: members (app_users) get full CRUD — working data, mirroring
--  projection_reports / service_memos. New table => policies added in
--  this same migration or the app can't read it at all (§6.6).
--
--  Rollback: db/2026-07-26_financial_statements_rollback.sql
-- ════════════════════════════════════════════════════════════════════

create table if not exists public.financial_statements (
  id            bigint generated by default as identity primary key,
  client_id     bigint references public.clients(id) on delete set null,
  company_name  text   not null,                       -- snapshot at save time
  pan           text,                                  -- snapshot
  fiscal_year   text   not null,                       -- dash format, e.g. '2082-83'
  basis         text   not null default 'provisional'
                  check (basis in ('provisional', 'audited')),
  return_type   text,                                  -- D1 / D2 / D3 / D3V
  entity_type   text,                                  -- snapshot of the profile used
  inputs        jsonb  not null default '{}'::jsonb,
  computed      jsonb  not null default '{}'::jsonb,
  created_by    text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

comment on table public.financial_statements is
  'Saved NFRS financial statement sets (Financial Statement module): prior-year comparative + figures A-N in `inputs`, solved statements in `computed`.';

-- One saved working per client, year and basis: re-running overwrites
-- rather than accumulating near-duplicates, and a client may hold both a
-- provisional and an audited set for the same year.
create unique index if not exists financial_statements_client_fy_basis_idx
  on public.financial_statements (client_id, fiscal_year, basis)
  where client_id is not null;

create index if not exists financial_statements_fy_idx      on public.financial_statements (fiscal_year);
create index if not exists financial_statements_created_idx on public.financial_statements (created_at desc);

-- ── updated_at maintenance (reuses the shared trigger fn) ──
drop trigger if exists set_financial_statements_updated_at on public.financial_statements;
create trigger set_financial_statements_updated_at
  before update on public.financial_statements
  for each row execute function public.set_updated_at();

-- ── RLS: full member CRUD. Non-members / anon get zero rows. ──
alter table public.financial_statements enable row level security;

drop policy if exists financial_statements_select_member on public.financial_statements;
create policy financial_statements_select_member on public.financial_statements
  for select to authenticated using (private.is_app_user());

drop policy if exists financial_statements_insert_member on public.financial_statements;
create policy financial_statements_insert_member on public.financial_statements
  for insert to authenticated with check (private.is_app_user());

drop policy if exists financial_statements_update_member on public.financial_statements;
create policy financial_statements_update_member on public.financial_statements
  for update to authenticated using (private.is_app_user()) with check (private.is_app_user());

drop policy if exists financial_statements_delete_member on public.financial_statements;
create policy financial_statements_delete_member on public.financial_statements
  for delete to authenticated using (private.is_app_user());
