-- ════════════════════════════════════════════════════════════════════════════
--  STAGE 2 · PHASE 1 — tenant scaffold. Nothing is enforced yet.
--
--  Part of converting this app from one firm to ~10. Full scope:
--  https://claude.ai/code/artifact/c372d471-8003-4d50-8bd7-92197ee2094c
--
--  WHAT THIS DOES
--    1. Creates organizations / org_members / org_firms.
--    2. Seeds THE one organisation that exists today, its 3 members and its
--       5 letterheads.
--    3. Creates private.current_org_id().
--    4. Adds a NULLABLE org_id + index to all 22 tenant-owned tables.
--
--  WHAT IT DELIBERATELY DOES NOT DO
--    · Does not backfill org_id (Phase 2).
--    · Does not set NOT NULL (Phase 3).
--    · Does not touch the 82 existing policies (Phase 3), so every existing
--      query behaves exactly as it does today. This file is additive.
--    · Does not touch app_users. It stays readable and is what
--      private.is_app_user() still checks, so sign-in is unaffected. It is
--      the rollback path until Phase 3 cuts membership over to org_members.
--
--  ORDER IS LOAD-BEARING: organizations before org_members (FK), org_members
--  before current_org_id() (the function's body is validated at CREATE time),
--  and current_org_id() before the SET DEFAULT statements that call it.
--
--  ON THE SEED DATA: the firm names, PANs and addresses below are the firm's
--  OWN registration details, already committed in js/config.js — they are not
--  client data, which never enters this repo (CLAUDE.md §1 rule 7).
--
--  ROLLBACK: db/2026-08-18_stage2_phase1_tenant_scaffold_rollback.sql
--  Safe to run at any point after this one — it drops only what this created.
-- ════════════════════════════════════════════════════════════════════════════


-- ── 1. The tenant root ──────────────────────────────────────────────────────
-- `status` is checked inside current_org_id() rather than only in the UI, so
-- suspending an organisation blocks it at the database (Stage 7 needs this;
-- building it in now costs one column).
--
-- `staff_names` holds what window.ARF_STAFF hardcodes today — the "who did
-- this work" picklist, which is per-practice. window.AQC_STAFF needs no home:
-- it is this list plus the firm names, which org_firms already has, so it can
-- be assembled at runtime instead of stored twice.
create table public.organizations (
  id          bigint generated by default as identity primary key,
  name        text not null,
  slug        text not null unique,
  status      text not null default 'active',
  staff_names jsonb not null default '[]'::jsonb,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  constraint organizations_status_check
    check (status = any (array['active','suspended']))
);

-- ── 2. Membership ───────────────────────────────────────────────────────────
-- Supersedes app_users, which knows who is staff but not WHOSE staff.
--
-- email is UNIQUE GLOBALLY, not per organisation. That is the constraint that
-- enforces the project's "one person belongs to exactly one organisation"
-- decision — with a per-org unique key the same address could join two firms
-- and current_org_id() would have no single answer.
create table public.org_members (
  id         bigint generated by default as identity primary key,
  org_id     bigint not null references public.organizations(id) on delete cascade,
  email      text not null unique,
  role       text not null default 'staff',
  status     text not null default 'active',
  invited_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint org_members_role_check
    check (role = any (array['owner','admin','staff'])),
  constraint org_members_status_check
    check (status = any (array['active','inactive']))
);

-- ── 3. Letterheads ──────────────────────────────────────────────────────────
-- One row per firm the practice issues documents under. This is
-- window.REP_FIRMS + window.SERVICE_MEMO_FIRMS + window.FINAL_ACCOUNT_FIRM_KEYS
-- turned into data.
--
-- firm_key keeps the EXACT strings already stored in service_memos.firm_key,
-- bank_accounts.firm_key and party_opening_balances.firm_key. Those columns
-- are plain text with no foreign key and stay that way in this phase: adding
-- one would be a second enforcement change on top of the tenant work, and
-- those three columns are already reachable only through an org-scoped row.
--
-- is_typed marks the 'other' entry, whose name is typed per memo rather than
-- configured (service_memos.firm_other). for_final_account is
-- FINAL_ACCOUNT_FIRM_KEYS — the Balance Sheet has exactly two columns.
create table public.org_firms (
  id                bigint generated by default as identity primary key,
  org_id            bigint not null references public.organizations(id) on delete cascade,
  firm_key          text not null,
  name              text not null,
  title             text,
  address           text,
  email             text,
  phone             text,
  reg_no            text,
  m_no              text,
  pan               text,
  cop_no            text,
  signatory_name    text,
  signatory_title   text,
  logo              text,
  name_np           text,
  auditor_name_np   text,
  title_np          text,
  memo_prefix       text,
  is_typed          boolean not null default false,
  for_final_account boolean not null default false,
  is_active         boolean not null default true,
  sort_order        integer not null default 0,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  constraint org_firms_org_key_uniq unique (org_id, firm_key)
);

create index org_members_org_idx on public.org_members using btree (org_id);
create index org_firms_org_idx   on public.org_firms   using btree (org_id, sort_order);

create trigger set_organizations_updated_at before update on public.organizations
  for each row execute function public.set_updated_at();
create trigger set_org_members_updated_at   before update on public.org_members
  for each row execute function public.set_updated_at();
create trigger set_org_firms_updated_at     before update on public.org_firms
  for each row execute function public.set_updated_at();


-- ── 4. Seed the one organisation that exists today ──────────────────────────
-- Shailesh & Associates (the son's CA firm) and Dallakoti & Company (his
-- father's audit firm) trade under separate letterheads but are one practice:
-- one office, one person doing the work, and — decisively for this model —
-- ONE shared client directory. clients has no firm column, so the 346 clients
-- cannot be split between them. Rename with a single UPDATE if wanted; nothing
-- keys off the name.
insert into public.organizations (name, slug, staff_names)
values ('Shailesh & Associates', 'shailesh-associates',
        '["Aadarsha","Kesav","Dipendra","Other"]'::jsonb);

-- Members carry over from app_users verbatim, including role. The senior
-- admin becomes 'owner'; app_users has no such role, and Stage 3's invitation
-- flow needs someone who can administer the organisation itself.
insert into public.org_members (org_id, email, role)
select o.id, u.email,
       case when u.email = 'dac.audit@gmail.com' then 'owner' else u.role end
from public.app_users u
cross join (select id from public.organizations where slug = 'shailesh-associates') o;

-- The five letterheads, mirroring js/config.js exactly.
insert into public.org_firms
  (org_id, firm_key, name, title, address, email, phone, reg_no, m_no, pan, cop_no,
   signatory_name, signatory_title, logo, name_np, auditor_name_np, title_np,
   memo_prefix, is_typed, for_final_account, sort_order)
select o.id, v.*
from (select id from public.organizations where slug = 'shailesh-associates') o,
(values
  ('shailesh', 'Shailesh & Associates', 'Chartered Accountants',
   'Khairahani-01, Chitwan', 'shailesh.2214@gmail.com', '9855062760, 056-562760',
   '619', '954', '604101019', '714',
   'Shailesh Dallakoti, CA', 'Proprietor', 'assets/logo-lockup.png',
   'शैलेश एण्ड एसोसिएट्स', 'शैलेश डल्लाकोटी', 'सीए',
   'SM-SA', false, true, 1),
  ('dallakoti', 'Dallakoti & Company', 'Registered Auditor',
   'Ratnanagar-02, Chitwan', 'dac.audit@gmail.com', '9855060014, 056-562760',
   '"B" 2716', '3105', '300336179', '148',
   'Devi Prasad Dallakoti, RA', 'Proprietor', null,
   'डल्लाकोटी एण्ड कम्पनी', 'देवी प्रसाद डल्लाकोटी', 'आर.ए.',
   'SM-DC', false, true, 2),
  -- The two sister concerns. Address/PAN are blank in config.js today and stay
  -- blank here; the memo PDF prints "—" until the firm fills them in.
  ('rosp', 'Ratnanagar Offset Screen Print', null,
   null, null, null, null, null, null, null,
   null, null, null, null, null, null,
   'SM-ROSP', false, false, 3),
  ('rtc', 'Ratnanagar Tax Consultancy', null,
   null, null, null, null, null, null, null,
   null, null, null, null, null, null,
   'SM-RTC', false, false, 4),
  -- The sheet's "other--Specify" row. Kept as a real row so firm_key stays a
  -- closed vocabulary; the displayed name comes from service_memos.firm_other.
  ('other', 'Other — specify', null,
   null, null, null, null, null, null, null,
   null, null, null, null, null, null,
   'SM-OT', true, false, 5)
) as v(firm_key, name, title, address, email, phone, reg_no, m_no, pan, cop_no,
       signatory_name, signatory_title, logo, name_np, auditor_name_np, title_np,
       memo_prefix, is_typed, for_final_account, sort_order);


-- ── 5. The one place tenancy is decided ─────────────────────────────────────
-- SECURITY DEFINER so it can read org_members regardless of that table's own
-- policies — the same pattern private.is_app_user() already uses, and what
-- keeps a policy that calls this from recursing into itself.
--
-- STABLE so Postgres evaluates it once per statement rather than once per row;
-- on a 5,639-row table that is the difference between a fast policy and a slow
-- one.
--
-- Returns NULL for a suspended organisation, an inactive member, or an unknown
-- email. Once Phase 3's policies compare against it, NULL matches no row —
-- suspension therefore blocks at the database, not in the UI.
create or replace function private.current_org_id()
returns bigint
language sql stable security definer set search_path to ''
as $function$
  select m.org_id
  from public.org_members m
  join public.organizations o on o.id = m.org_id
  where lower(m.email) = private.jwt_email()
    and m.status = 'active'
    and o.status = 'active'
  limit 1;
$function$;

revoke all on function private.current_org_id() from public;
grant execute on function private.current_org_id() to authenticated, service_role;


-- ── 6. RLS on the three new tables ──────────────────────────────────────────
-- A new table with RLS on and no policy is invisible to the app, so both go in
-- here together (CLAUDE.md §6). These are the only policies in Phase 1 that
-- are org-scoped from birth; the other 82 are rewritten in Phase 3.
alter table public.organizations enable row level security;
alter table public.org_members   enable row level security;
alter table public.org_firms     enable row level security;

create policy organizations_select_own on public.organizations
  for select to authenticated using (id = private.current_org_id());
create policy organizations_update_admin on public.organizations
  for update to authenticated
  using (id = private.current_org_id() and private.is_admin())
  with check (id = private.current_org_id());

create policy org_members_select_own on public.org_members
  for select to authenticated using (org_id = private.current_org_id());

create policy org_firms_select_own on public.org_firms
  for select to authenticated using (org_id = private.current_org_id());
create policy org_firms_insert_admin on public.org_firms
  for insert to authenticated
  with check (org_id = private.current_org_id() and private.is_admin());
create policy org_firms_update_admin on public.org_firms
  for update to authenticated
  using (org_id = private.current_org_id() and private.is_admin())
  with check (org_id = private.current_org_id());

-- org_members has deliberately NO insert/update/delete policy in this phase.
-- Adding a member is Stage 3's invitation flow; until then the only way in is
-- the Supabase dashboard, which is exactly the situation app_users is in today.

grant all on all tables    in schema public to anon, authenticated, service_role;
grant all on all sequences in schema public to anon, authenticated, service_role;


-- ── 7. org_id on all 22 tenant-owned tables ─────────────────────────────────
-- Every existing table except app_users, which org_members supersedes.
--
-- Two statements per table, deliberately not one:
--   ADD COLUMN with no default is a metadata-only change — it does not rewrite
--   the table. SET DEFAULT afterwards is also metadata-only and does NOT
--   backfill existing rows. Combining them into ADD COLUMN ... DEFAULT would
--   force a full rewrite of every table AND stamp every existing row with
--   whatever current_org_id() returns for the migration's own connection,
--   which is NULL. Phase 2 backfills explicitly instead.
--
-- The default is set NOW rather than in Phase 3 on purpose: any row the firm
-- creates between Phase 2's backfill and Phase 3's enforcement then gets its
-- owner automatically, so the backfill cannot be overtaken by ordinary use.
--
-- ON DELETE RESTRICT: deleting an organisation must not silently cascade away
-- its books. Deletion is Stage 7, and it is meant to be a deliberate,
-- rehearsed, export-first operation.
do $$
declare t text;
begin
  foreach t in array array[
    'clients', 'client_shareholders',
    'send_logs', 'audit_log',
    'service_memos', 'service_memo_fee_skips',
    'depreciation_schedules',
    'bank_accounts', 'bank_transactions',
    'party_opening_balances',
    'financial_statements', 'projection_reports',
    'document_register', 'saved_documents',
    'audit_report_finalization', 'audit_checklists',
    'work_done', 'work_todos',
    'autobooks_books', 'autobooks_entries',
    'autobooks_parties', 'autobooks_adjustments'
  ] loop
    execute format(
      'alter table public.%I add column org_id bigint
         references public.organizations(id) on delete restrict', t);
    execute format(
      'alter table public.%I alter column org_id set default private.current_org_id()', t);
    execute format(
      'create index %I on public.%I using btree (org_id)', t || '_org_idx', t);
  end loop;
end $$;


-- ── 8. Verify ───────────────────────────────────────────────────────────────
-- Expect, measured on the staging rehearsal:
--   orgs 1 · members 3 · firms 5 · fn_exists t
--   org_id_columns 24 · org_indexes 24 — twenty-two tenant tables PLUS
--     org_members.org_id and org_firms.org_id, which are those tables' own
--     foreign keys and are not part of the 22.
--   with_default 22 — this is the number that pins the tenant tables exactly,
--     since only they get private.current_org_id() as a default.
--   policies 88 — the 82 that already existed, untouched, plus 6 new.
--
-- org_id is NULL on every existing row at this point. That is correct: nothing
-- reads the column yet, and Phase 2 is what fills it.
select
  (select count(*) from public.organizations)                          as orgs,
  (select count(*) from public.org_members)                            as members,
  (select count(*) from public.org_firms)                              as firms,
  (select count(*) from information_schema.columns
     where table_schema='public' and column_name='org_id')             as org_id_columns,
  (select count(*) from information_schema.columns
     where table_schema='public' and column_name='org_id'
       and column_default is not null)                                 as with_default,
  (select count(*) from pg_indexes
     where schemaname='public' and indexname like '%\_org\_idx')       as org_indexes,
  (select count(*) from pg_policies where schemaname='public')         as policies,
  (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace
     where n.nspname='private' and p.proname='current_org_id'))        as current_org_id_exists;
